### ISSUE TITLE
Project Direction

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#1]
I was going to write my own Vue wrapper for MDC when I stumbled across this repo. There's no point duplicating that work so I'd like to help develop this project.

What do you envision the final product looking like? How would a Vue dev use that final product?

I think we should also add some sort of checklist for components so its easy to see what still needs to be added.

**Comment by stasson** [comment]
Hi, 

I'd welcome any help. You may want to check the [vue_mdc](https://github.com/posva/vue-mdc) project first. It is in a more advanced stage and I really like it. Although it doesn't seem to use MDC's javascript much. Not a big deal if you do not care about ripples and transitions, but I wanted to try the full MDC experience...

This is a project I started for fun with the goal of learning vue and material design. But I'm beginning  to think it's worth to get a bit more serious. What I have in mind for the final product is a library like [vue_material](https://vuematerial.github.io) implemented on top of MDC, with MDC's javascript support ( aka use foundations wherever possible ... ) 

The target of the library is dektop, web and hybrid apps. The plan is to align the feature set on [MDC](https://material-components-web.appspot.com). it would be available as an npm package, and on a cdn (probably unpkg) with a demo/doc website. I do not plan to go as far as delivering separate npm packages for each component/module yet (unless someone is desesperate for it...)

I want to keep the components as simple to use as possible and to stick to the "vue spirit" approachable, versatile, performant.

My plan was to finish a first version of mdc-dialog, mdc-toolbar, mdc-drawer and mdc-select which I'm missing. then to write doc and then to work on production scripts. I was targeting a first alpha beginning of july. 

The design is definitely not settled and I'm afraid I'll have to do some breaking changes soon... That's probably where I need more help right now: I'm not really happy with some of the components markup, and I'll welcome any feedback.

Right now I have only been in a development frenzy. I have not put much thoughts in the next steps and how to setup collaboration. Let me think a bit about it and come back to you on that.

Seb

**Comment by griest024** [comment]
> delivering separate npm packages for each component/module

I agree that this is not the right way to go. While it makes sense for the main MDC package to deliver each component separately, anybody who is already using Vue should find it simple to import individual components as they need them from a single npm package.

> the full MDC experience

Yes, ideally I would like to have adapters implemented for *every single* foundation that MDC provides and  even some additional components for special use cases/ease of use.

From what I see of vue_mdc, it doesn't look like this is the intention of the project, although that may be because its been adapted from a Vue MDL project. 

For example, their [Toolbar implementation](https://github.com/posva/vue-mdc/tree/master/src/Toolbar) doesn't use the foundation at all, instead using render functions. This seems to go against the principles of Vue and MDC and is something I would like to avoid whenever possible. Still, I think there is some code in there worth stealing.

> My plan was to finish a first version of mdc-dialog, mdc-toolbar, mdc-drawer and mdc-select

I'm already working on the toolbar and drawer. If everything goes well (lol) I should be ready to submit a PR tonight.

**Comment by stasson** [comment]
I have setup the wiki with project direction, checklist's and initial roadmap

**Comment by griest024** [comment]
Looks good so far. I have some ideas that may clarify the vision for this project, let me know what you think.

I think this project should aim to accomplish 2 things:

1. At its most minimal, vue-mdc-adapter should be a very thin layer between a Vue dev and MDC. This thin layer shouldimplement Vue adapters for every MDC foundation available. It should also enable the dev to use every single feature of MDC without actually touching a MDC component themselves (in JS). This layer should aim to be as thin as possible in order to restrict the dev as little as possible (ideally not at all) and make as little design decision as it can. That is, the layer is really nothing more than a wrapper around MDC.

2. In addition to providing the adapters, I think vue-mdc-adapter should provide components for common-use cases. These components should save the dev from writing boilerplate code and implementation that is very common. These components will make some design decisions for the dev, and therefore restrict him/her somewhat.

Vue-mdc-adapter should be completely functional in the first mode, so that the Vue dev can completely customize the behavior of MDC with the second mode being sugar on top.

Check out the PR I submitted.

**Comment by stasson** [comment]
Agreed on the two level of usage:
* advanced usage: 
  - thin layer / great perf
  - allows devs to fully customize but they need to understand mdc

* basic usage: 
  - provide support for all componnents but may be not all use cases and may have to sacrifice little bit 
    of perf.
  - no need to fully understand mdc ( aka no need to dig in mdc's doc or css files to use this project )

After it's all about where you put the trigger:  do we go all the way to separate in two layers or do we keep same component for the two aproaches, does the perf really matter, etc ...

I'm still digesting this and I think I need to go through some use cases... we can still refactor little bit later anyway. vue dev is really fast :)


On a side note: I have added a "Guideline" page on the wiki to capture our discussions... 
let me know...

**Comment by griest024** [comment]
Perhaps we should consider having 2 separate projects. This project could focus only on implementing adapters, as suggested by the title. The framework would rely on this project, and provide more Vue-specific features and enable the user to use MDC without touching MDC itself. like you say:

> no need to dig in mdc's doc or css files to use this project

This would mean we could deliver both projects as a separate npm package, which should help devs who only want the adapters, and like @amc1999, already have a chaotic dependencies. Not only that, but having 2 projects would *strictly* enforce decoupling and modularity between the 2 projects (at least in 1 direction).

In addition, it would allow us to enforce stricter rules on the adapters. I imagine something like:

> An adapter template can only consist of a single `<div>` or `<span>` element containing a single `<slot>` element.

Rules like this would ensure that we aren't making any design decisions for the user in the adapters. It would also allow us to be laxer with those types of rules in the framework project. We can be free to add as much robustness as we want to the framework without fear of polluting the adapter library. Not only that, but other projects could use the adapter library without having to deal with our framework code.

**Comment by griest024** [comment]
@stasson wiki looks good, don't forget the check "drawer". 

We also need to consider how we are going to handle cases where there are multiple versions of components, i.e. temporary drawer vs persistent and fixed, waterfall, flexible, etc. toolbars. Theoretically you could handle all those cases with a single adapter, but it might be cleaner to have a base adapter and extend that for each component version.

**Comment by amc1999** [comment]
> having 2 projects would strictly enforce decoupling and modularity between the 2 projects

very good idea

> An adapter template can only consist of a single <div> or <span> element containing a single <slot> element.

It may lead to flood of micro-components which do exist only to serve as sub-components for "real" parent component, ex.: drawer with toolbar and / or header slots.

**Comment by amc1999** [comment]
> @griest024 Theoretically you could handle all those cases with a single adapter, but it might be cleaner to have a base adapter and extend that for each component version

Taking temporary vs persistent vs permanent drawers as example: mixin of styles and APIs can make component adapter very difficult to read and understand, unless it is documented and `util`'ized on same level as MDC, which may be a problematic with limited project development resources.

**Comment by griest024** [comment]
> It may lead to flood of micro-components which do exist only to serve as sub-components for "real" parent component

I do believe that would be the intention. The *only* purpose of my proposed adapter project would be to provide (JS) Vue implementations of the foundations. Any assumptions about the use of the adapter, i.e. if the drawer is used with a toolbar, or about any of the content itself, should be contained within the framework.

Its certainly reasonable to provide support for those cases in the adapter. In fact, my preliminary work on the toolbar suggests that its necessary, but making any assumptions about the content of the components seems to be beyond the scope of the adapter project. I'm not sure if the components need a template at all, maybe it would be better to restrict ourselves to only JS in the adapter library.

@amc1999 Look at [my first draft of `mdc-toolbar`](https://github.com/griest024/vue-mdc-adapter/blob/feature/mdc-toolbar/src/components/toolbar/mdc-toolbar.vue). I do provide some "sugar" slots for the common-use cases, and then have a fallback slot for those that need a higher level of customization. I think all the sugar should be extracted to the framework as even though it doesn't `force` the user into any decisions, its not necessarily within the scope of the adapter library.

Ideally I would like the library to be a canonical Vue implementation of MDC, and therefore should aim to be as abstract as possible so it could serve as the base for any number of Vue MDC frameworks.

> mixin of styles and APIs can make component adapter very difficult to read and understand, unless it is documented

I intend to document the adapters very well, and the framework project would serve and an example usage of the adapters. However, you are correct, the complexity can rise very quickly. This matter definitely requires more thought and discussion.

**Comment by amc1999** [comment]
> Ideally I would like the library to be a canonical Vue implementation of MDC

that what I am looking for, thank you

> [my first draft of mdc-toolbar](https://github.com/griest024/vue-mdc-adapter/blob/feature/mdc-toolbar/src/components/toolbar/mdc-toolbar.vue) ...  I do provide some "sugar" slots for the common-use cases, and then have a fallback slot for those that need a higher level of customization

yes, I would expect very similar template and my original response was only to loosen up
> adapter template can only consist of a single slot

restriction, nothing else. 
feel free to ignore :)

**Comment by griest024** [comment]
> loosen up restriction

This is actually a good point. I am somewhat conflicted about this. Here are my thoughts:

Pro-restriction: I am thinking that restriction in this manner would help enforce the design of the adapters to the very specific scope of the adapter library. While I am very much against restriction in software development, I think restricting the *design* of the adapters would actually cause more freedom in the *use* of the adapters. Its the use cases in which we need to maximize freedom and customization.

Anti-restriction: On the other hand, we could loosen the restriction to read:

> An adapter template must be a single `<div>` or `<span>` element containing a single `<slot>` element

This way, each adapter is guaranteed to be usable in "max customization mode", while still offering helpful features.

However, you yourself said that you are concerned with "piling up integration issues" by including more dependencies. By restricting the scope of this project, we remove the temptation to introduce code that can destroy the decoupling between the adapter and the framework.

Personally, I'm on board with supporting common-use cases in the adapter, but I think as much of that functionality as possible should be moved to JS.

**Comment by griest024** [comment]
Here is something else to think about. MDC itself is going to change quite a lot, its only version 0.11.1. The foundations aren't really that polished yet. By restricting the code we are allowed to write in the adapters, we ensure maximum maintainability.

**Comment by amc1999** [comment]
> we remove the temptation to introduce code that can destroy the decoupling between the adapter and the framework

From my point decoupling adapters from framework is fundamental and should be enforced. This is a cornerstone. 

> single slot (div, span) 

I don't really have any strong preference and leaning towards your current toolbar and  stasson's drawer with `$slots` which very much in sync with underlying MCW components design. I would say slots is necessary in that case (all that just a discussion point, not a final verdict :)

Personally, I have no problem to `import  mdc-menu-item` and `mdc-menu-anchor` separately from `mdc-menu` but not always see a clear case for that. Again, it is not an issue for me, just an attempt not to multiple instances beyond necessity.

> MDC itself is going to change quite a lot... ensure maximum maintainability

true, that is one of the reason why I do look at vue-mdc-adapter and hope to find canonical Vue implementation of MDC adapters which I can use for years in my MIT-licensed project.

**Comment by griest024** [comment]
>  I have no problem to import mdc-menu-item and mdc-menu-anchor separately from mdc-menu

Well some of the micro-components and mixins would be for internal use only, hopefully the components you would import would be more unified.

**Comment by griest024** [comment]
> I don't really have any strong preference and leaning towards your current toolbar and stasson's drawer with $slots which very much in sync with underlying MCW components design. I would say slots is necessary in that case

This will for sure be one of the most important design decisions we make, and I suspect it will evolve as we develop the project and explore more use cases. I need to let it marinate for while, but I hope to come up with some good solutions on that front.

**Comment by stasson** [comment]
@griest024 and @amc1999 

I have been pretty busy lately so sorry for late reply...

Regarding the project direction here are my thoughts at the moment:

**Comment by stasson** [comment]
@griest024 and @amc1999 

I have been pretty busy lately so sorry for late reply...  
Regarding the project direction here are my thoughts at the moment:

> it would be great to keep vue-mdc-adapter as "library" vs "framework".

I'm not sure where the distinction being framework and library is. I think the project will stay a library in the sense that it will only wrap mdc components not more, not less. For the bundling, I keep vue as an external library. For the moment I'll keep MDC bundled to be sure the adapters are aligned on specific packages versions, and because I don't want to import full MDC, just the foundation, the css and couple components. 

I still want to keep the 2 usage of the library: experts users can customize fully while beginners or "lazy" users can _easily_ get a result.  By _easily_ I mean a user shouldn't have to understand css/js details of mdc to achieve a result. The API (props and markup exemples) should be enough. 

But it won't be a framework in the sense that I think to provide the building blocks for user to build their own components. for example for list or menu, I think the "adapter" shouldn't implement the v-for and the binding to the list items. up to the user to create it's own generic list component using the building blocks. I hope we can achieve this (although I admit it can become verbose, and it'll bring some serious design constraints ...)

> Perhaps we should consider having 2 separate projects.  

This is a direction I am not comfortable with. It seems to me it would be a lot of work and I'm not sure it is necessary.


You raised many good points and it gave me a lot to think, and I now have a better idea about what I want for the design/direction. Here some those ideas:

- avoid named slots to not impose the dom structure. one only slot rule

- each component should have a class matching component name 

- split the plugin into feature so that users can include all or on a feature basis without having to import each of the subcomponents manually. (I think I'll keep only one npm package though.)

- try to keep the API and the implementation (props and markup) as simple as possible without adding any extra feature. 

I still have some refactoring to do to get there though... And I know this project won't go anywhere without some clean documentation and won't survive MDC upgrades without some strong UT suite.
We'll get there ...

**Comment by amc1999** [comment]
> framework vs library

I would call it a library as long as it is a collection of (almost) independent parts, i.e. adapters for each MDC component, and I can use it without being forced to certain app structure behind the scene. Something like a collection of canonical vue+MDC wrappers. As far as I understand vue-mdc-adapter fits that definition.

**Comment by griest024** [comment]
@stasson You claim that you want:

> a user shouldn't have to understand css/js details of mdc to achieve a result.

However, I can't see how to achieve this without either passing in elements through props, which is advised against, or using named slots. I am interested to hear your ideas on how this can be accomplished. 

Now while I agree that *forcing* users into a particular DOM structure is wrong and should be avoided at all costs, using named slots doesn't force the user into anything as long as there is an unnamed slot. So I propose this following restriction:

> An adapter template must contain an *unnamed* `<slot>` element

With this simple restriction, we ensure that every component is usable in "custom" mode, while allowing the freedom for us devs to add named slots or whatever else we need to facilitate "lazy" use.

Once again, I think named slots should absolutely be used for "lazy" mode, as I can't think of any way (or reason) to avoid imposing DOM structure on a component when used in "lazy" mode. Additionally, slots are inherently a Vue idiom, and replacing them with things like `querySelector`s and other DOM operations brings this project further away from the goal of being an canonical Vue implementation of MDC.

**Comment by stasson** [comment]
@griest024 

> a user shouldn't have to understand css/js details of mdc to achieve a result.

I just meant  users of the library should not need to go through MDC docs and code to understand what needs to done to achieve a result.  so we need to keep simple straightforward APIs and document well . 

> avoid named slots to not impose the dom structure. one only slot rule

The issue I have with named slots is with components like mdc-card: you may want to have a media block arround the header or before the header. Achieving this flexibility with slots is way too complex and I ended up writing so many  "_companion components_" () for mdc_card. This is a verbose solution and I do admit those "_companion_ components" are just wrapping MDC's css. But I did it so the user does not have to read MDC's doc.

May be I'm overthinking this and the question of named slots vs more markup could be taken on a component basis. Although I'm also looking for consistency in the component API's and design patterns 

Anyway, Now that I got the build env and the the preview site cleared, I think I'll undergo some refactoring of the components within the next couple of weeks. I want to start freezing APIs and then go for a more controlled pace and stop changing the code every where. 

I also want to start doc and UT. Doc is a priority and will go first I think. ( yes I know it's bad to not do ut first ...)

**Comment by griest024** [comment]
> This is a verbose solution and I do admit those "companion components" are just wrapping MDC's css.

I found myself writing many micro-components that are just wrapping CSS as well. However, I think this is not a bad thing, as long as lazy mode provides a way to avoid using most of those components. The price of customization is verbosity.

I don't care about using named slots if there is a better solution. I think the lazy mode implementation will certainly vary based on component. Custom mode however should have stricter rules to make sure we are ensuring user freedom as much as possible while achieving consistency in API and design patterns..
