### ISSUE TITLE
Use yarn for dependency management

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#104]
https://yarnpkg.com

Yarn is faster and deterministic. It verifies package integrity for every download among other improvements over npm.

You could still use npm alongside yarn but you should checkin the `yarn.lock` file to git.

**Comment by stasson** [comment]
works for yarn, just need to find a way to update both yarn and npm lockfiles in the ci.

**Comment by griest024** [comment]
@stasson just run `yarn` and it will generate the lockfile. Why do you need to do that in ci though? Is it something to do with greenkeeper?

**Comment by stasson** [comment]
2 issues : 
- once I get yarn.lock, travis uses it instead of npm not sure how to force npm5
- how can I get greenkeepeer to save both npm and yarn lock file in one pass.

need to investigate further

**Comment by griest024** [comment]
What does explicitly running `npm i` in the script do?

**Comment by stasson** [comment]
@griest024 

I'm dropping this one. I was not able to setup travis to update both yarn lock and npm lockfile at the same time :( 
So I'm sticking to npm for now.

**Comment by griest024** [comment]
@stasson that's a shame, yarn really is superior. I understand though, maybe later.
