### ISSUE TITLE
Dialog: prevent escape key from triggering onCancel

### ISSUE THREAD

**Issue by hanxue** [stasson/vue-mdc-adapter#110]
I am using `mdc-dialog` to obtain user input, and the text-area content is bound to a vue variable. 

This is what I need after the Dialog is open:

1. User press <kbd>Esc</kbd>, dialog closed but `@cancel` not triggered
2. User press `Cancel` in Dialog, call `@cancel`, vue will clear the text-area bound variable

How can I achieve that?

**Comment by stasson** [comment]
@hanxue 

`mdc-dialog`component is using mdc foundation which will always trigger cancel on <kbd>Esc</kbd>.
So changing the keys behavior requires is not easily feasible.

What I could do though is to allow you to customize your footer and provide sub-components for your own buttons. You would then be able to create your `my-own-cancel` event so you can customize the behavior. You would ignore  the legacy `cancel` which will be triggered anyway.

Would this work for you ? 

Also I am curious about the use case ? Do you handle the input variables differently for <kbd>Esc</kbd> vs click on  cancel ?

**Comment by stasson** [comment]
@hanxue 

let me know if this work for you and how urgent it is so I can plan the change.

txs

**Comment by stasson** [comment]
@hanxue 

I'm closing the issue. Please reopen the issue if you ever wnated the change
