### ISSUE TITLE
Unknown custom element: <mdc-toolbar-icon-menu>

### ISSUE THREAD

**Issue by Bobarev** [stasson/vue-mdc-adapter#113]
In your [usage](https://github.com/stasson/vue-mdc-adapter/tree/master/components/toolbar) example:

```
<mdc-toolbar>
  <mdc-toolbar-row>
    <mdc-toolbar-section align-start >
      <mdc-toolbar-icon-menu event="toggle-drawer"></mdc-toolbar-icon-menu>
      <mdc-toolbar-title>Title</mdc-toolbar-title>
    </mdc-toolbar-section>
    <mdc-toolbar-section align-end>
      <mdc-toolbar-icon event="show-help" icon="help"></mdc-toolbar-icon>
    </mdc-toolbar-section>
  </mdc-toolbar-row>
</mdc-toolbar>
```
**Unknown custom element: <mdc-toolbar-icon-menu> - did you register the component correctly? For recursive components, make sure to provide the "name" option.**

On the demo site you use:
`<mdc-toolbar-menu event="toggle-drawer"></mdc-toolbar-menu>`

**Comment by stasson** [comment]
@Bobarev 

Component name in the doc is wrong, should be `mdc-toolbar-menu`. 
https://codepen.io/stasson/pen/MOOoRP

Having a look as latest MDC code, I guess the right component name should be `mdc-toolbar-menu-icon` to avoid any confusion with menu. 

Thanks a lot for bringing this to me. I'll fix this asap.
