### ISSUE TITLE
File to import not found or unreadable: vue-mdc-adapter/components/styles.

### ISSUE THREAD

**Issue by Bobarev** [stasson/vue-mdc-adapter#115]
In your [usage SCSS Theming](https://github.com/stasson/vue-mdc-adapter) example:

```
$mdc-theme-primary: #212121;
$mdc-theme-accent: #41B883;
$mdc-theme-background: #fff;

@import "vue-mdc-adapter/components/styles";
```
**File to import not found or unreadable: vue-mdc-adapter/components/styles.**

**Comment by stasson** [comment]
I can see `components/styles.scss` in the distribution. so it should work for you.
can u plz check the path is in your `node_modules`. 

you need to add `node_modules` include location to your sass config. That may be your issue

**Comment by Bobarev** [comment]
@stasson 
You're right. It turned out to be a non-trivial task to make the vue-loader handle the folder node_modules. Specially created a template based on [webpack-simple](https://github.com/vuejs-templates/webpack-simple), so that you can quickly start a project using your library:

> $ npm install -g vue-cli
> $ vue init Bobarev/vue-mdc-adapter-webpack-simple my-project
> $ cd my-project
> $ npm install
> $ npm run dev

https://github.com/Bobarev/vue-mdc-adapter-webpack-simple
