### ISSUE TITLE
How to use the individual component in VUE-component ?

### ISSUE THREAD

**Issue by Bobarev** [stasson/vue-mdc-adapter#116]
I earned only this way:
```
<template>
  <div id="app">
    <mdc-button raised>click me</mdc-button>
  </div>
</template>

<script>
import MdcButton from 'vue-mdc-adapter/components/button/mdc-button'

export default {
  name: 'app',
  components: {
    MdcButton
  }
}
</script>

<style lang="scss">
@import "vue-mdc-adapter/components/button/styles";
</style>
```
P.S. In your [cherry pick components](https://github.com/stasson/vue-mdc-adapter) example:
`@import "vue-mdc-adapter/components/button/mdc-button";`
_File to import not found or unreadable_

Must be:
`@import "vue-mdc-adapter/components/button/styles";`

**Comment by stasson** [comment]
@Bobarev 

I have refactored the way the distribution exports components.
I have added a detailed documentation in the new doc
see the [getting-started](https://stasson.github.io/vue-mdc-adapter/#/docs/getting-started) guide

I'm closing the issue. let me know if any issues
