### ISSUE TITLE
`toolbar` classes not being updated when using hot module replacement

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#13]
If I make a change to one of the props in `mdc-toolbar`, for example.

`<mdc-toolbar :waterfall="true" ...>` and then run my project. After making this change: `<mdc-toolbar :waterfall="false" ...>`, and saving the change, forcing recompilation, `rootClasses` and the element's class do not get updated

**Comment by griest024** [comment]
This should also allow hot module replacement to work, the classes are not being updated as it is.

**Comment by griest024** [comment]
I can see 2 ways to fix this.

In `components/toolbar/mdc-toolbar.vue`:

1. Add watchers to the props and update `rootClasses` with new value.
2. Use computed properties instead of data, and perform the appropriate operations on them in `addClass()`, `removeClass()`, and `hasClass()`.

I think 1 will be more syntactically concise.

**Comment by stasson** [comment]
I'm not sure this such a good idea:
1.  It'll make the way the foundation add/remove and check for classes more complex. and I want to keep the implementation lightweight.
1.  for me, the `fixed waterfall fixed-lastrow flexible flexible-default` are meant to be static attributes, not meant to be dynamic properties that can be bounded. we don't want to change the type of toolbar dynamically, do we ? 
1. hot replacement is used just for dev, pressing F5 should re-render. so is this that big of an issue ?

**Comment by griest024** [comment]
1. I found a fairly simple way to do it, look at #14. The foundation interacts with `rootClasses` and then the computed classes merges `rootClasses` with the `props`.

> we don't want to change the type of toolbar dynamically, do we

2. This adapter is not just for us. Its meant to be a canonical Vue implementation of MDC, and therefore should offer maximum customization. I could certainly imagine a scenario where *someone* might want to change the behavior of the toolbar dynamically. And we aren't losing anything with this, only adding a feature.

3. Re-rendering could cause expensive operations to run again, whereas HMR will only update the module that need it, and won't re-render the entire app. For huge apps and complex use-cases, this could be a huge issue.
