### ISSUE TITLE
show dialog - delay?

### ISSUE THREAD

**Issue by diomed** [stasson/vue-mdc-adapter#130]
dialog component shows so fast, maybe even a bit too fast.
if there is a way you should delay if for a bit.

**Comment by griest024** [comment]
Wow I don't think I've ever had someone complain that a library was too fast.

Let me see if I understand you correctly, you are saying that from the time from when `dialog.show()` is called and the dialog appears on the screen is not long enough? I'm interested in your use case here.

**Comment by stasson** [comment]
@diomed 

this project relies on https://github.com/material-components/material-components-web/ for style and behaviour.  Doen't seem to be a bug. timings look similar to [ MDC Web demo](https://material-components-web.appspot.com/dialog.html)

so you should be able to customize their [styles](https://github.com/material-components/material-components-web/blob/02fe795139ed2fb3077008feaa52aaa928d014f5/packages/mdc-dialog/mdc-dialog.scss#L158)

right now they set the animation to 120 ms.

it's indeed a little bit fast.  according to [material design](https://material.io/guidelines/motion/duration-easing.html#duration-easing-common-durations), should be 150 to 200 ms on Desktop.
and even slower on mobile...

**Comment by diomed** [comment]
it's unnatural how fast it shows, like a jump scare in a horror movie 😄 
but yeah, you're right, this is not really a bug, and I can delay it myself,
now that I know where to look. so, thanks. this is solved.
