### ISSUE TITLE
change drawer type based on screen aspect ratio

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#132]
Instead of checking for a maximum of minimum number of pixels I think it makes more sense to check the aspect ratio of the window, or maybe a combination of those factors. On a 9:16 desktop screen I think it makes more sense to have a temporary drawer than a persistent one.

Alternatively, we could add a `drawer-type` prop to `mdc-drawer` that accepts a string which would simplify manually switching between drawer types with user defined logic.

**Comment by stasson** [comment]
Do agree on  `drawer-type="persitent"`.  should simplify the  code as well.
BREAKING_CHANGE though

changing media queries: I'm not sure. I'd like to stay align on MDCWeb mobile - tablet - desktop breakpoints for now. It's not ideal but I think we'd need a more framework aproach to responsiveness...
I think I'll start a discussion on their website

**Comment by griest024** [comment]
I'll start a PR for `drawer-type`
