### ISSUE TITLE
freeze api' reqs

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#134]
As was discussed in #111, there are some component properties that should be reactive and are not. We should identify them here and discuss the correct way to implement the reactive functionality. We should interact with the foundation where appropriate.

- [x] mdc-button
- [ ] mdc-card
- [ ] mdc-dialog
- [ ] mdc-drawer-list
- [ ] mdc-fab
- [ ] mdc-grid-list
- [ ] mdc-icon-toggle
- [ ] mdc-linear-progress
- [ ] mdc-list-divider
- [x] mdc-list
- [ ] mdc-menu
- [ ] mdc-radio
- [ ] mdc-slider
- [ ] mdc-snackbar
- [x] mdc-switch
- [ ] mdc-tab-bar
- [x] mdc-textfield
- [ ] mdc-toolbar-section
- [ ] mdc-toolbar

This list is very inclusive. These are only the components that are worth investigating, not necessarily those that need changes.

**Comment by stasson** [comment]
ok

**Comment by griest024** [comment]
@stasson you want separate issues for each component?

**Comment by stasson** [comment]
@griest024  

First we  track needed changes to be done in this issue and when we aggree on one component and are ready to implement we can open a feat/refactor issue  for the component.

**Comment by stasson** [comment]
let's start with mdc-button

| prop | reactive | Type | Default | Description |
|-------|------|------|---------|-------------|
|`disabled`| [x]| String|| disable the button |
|`raised`| |Boolean|| a contained button that is elevated upon the surface  (*)|
|`unelevated`| | Boolean|| a contained button that is flush with the surface (*)|
|`stroked`| | Boolean|| a contained button that is flush with the surface and has a visible border(*)|
|`dense`| | String||  compresses the button text to make it slightly smaller (*)|
|`compact`| |Boolean|| reduces the amount of horizontal padding in the button (*)|
|`event`|[x]|String| optional | optional event to emit on click  |
|`event-target`|[x]|Object| vm.$root | optional event target, defaults to root bus |
|`event-args`|[x]|Array|  | optional event args |
|`href`|[x]|String|| link's href, renders anchor (see notes below) | 

> Missing router-link props

> should add back accent theme (class removec from MDC but same as MDC Demo)
ref: <https://github.com/material-components/material-components-web/blob/7a23183d95bd88534db2939c04a5fc3faf46a3ad/demos/button.scss#L26>
```javascript
{
themeSecondary: Boolean
}
```
themeSecondary should be reactive I guess ?

**Comment by stasson** [comment]
so you want raised, unelevated, stroked, dense and compact to be reactive ?

**Comment by griest024** [comment]
> so you want raised, unelevated, stroked, dense and compact to be reactive ?

Yes I think that would be good. I think I'll benchmark reactive components tonight to see exactly how much of a performance cost it is.

**Comment by stasson** [comment]
no need to benchmark, I agree. I guess I'll start a bunch of mixins to ease implementation

**Comment by griest024** [comment]
@stasson Mixins for what exactly? Theming stuff?

Should I start implementing reactive for the button or do you want to handle everything in a single PR?

**Comment by stasson** [comment]
I'll do one PR for all buttons and derivatives (card buttons, fabs, ...)

**Comment by stasson** [comment]
- [x] mdc-button

**Comment by stasson** [comment]
closing this  one for now. will manage each issue on a per component basis
