### ISSUE TITLE
Checkbox throws error "Cannot read property 'addEventListener' of undefined" if no label

### ISSUE THREAD

**Issue by pgbross** [stasson/vue-mdc-adapter#135]
### What vue-mdc-adapter Version?
0.5.3

### What are the steps to reproduce the bug?
1. Use mdc-checkbox without a label.
```
<mdc-checkbox v-model="selected"></mdc-checkbox>
```
2. Render the page
3. Observe in console or otherwise the error `TypeError: Cannot read property 'addEventListener' of undefined`

### What is the expected behavior?
When there is no label the checkbox should not throw an error.

### What is the actual behavior?
The error is thrown when the ripple adapter is trying to add an event listener.

### Any other information you believe would be useful?
The component correctly has a `v-if` conditional in the `mdc-checkbox` template to prevent the html `label` element from rendering if it is not specified,  however both the `registerInteractionHandler/dergisterInteractionHandler` in the ripple adapter try and use the `this.$refs.label` object without checking if the label exists (lines 97 and 101).

**Comment by stasson** [comment]
will look into this

**Comment by stasson** [comment]
@pgbross 

how fast do you need the fix? should I point release now or can this wait next feature relase (within a week)?

**Comment by pgbross** [comment]
Happy to wait until next feature release. Thanks.
