### ISSUE TITLE
Can't compile - spread operator

### ISSUE THREAD

**Issue by coogle** [stasson/vue-mdc-adapter#138]
Hello,

I am trying to use this module in a Laravel app and using WebPack, and I can't seem to get it to work. I'm getting the following error:

```
ERROR in ./node_modules/vue-mdc-adapter/components/util/link.js
Module parse failed: Unexpected token (19:35)
You may need an appropriate loader to handle this file type.
|       // router-link case
|       element = this.$root.$options.components['router-link']
|       data.props = {tag: this.tag, ...this.link}
|     } else {
|       // element fallback
 @ ./node_modules/vue-mdc-adapter/components/util/index.js 5:0-25
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],"es2015","stage-3"],"plugins":["transform-object-rest-spread","transform-es2015-destructuring","transform-object-rest-spread","syntax-object-rest-spread","transform-object-assign","transform-es2015-parameters"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/vue-mdc-adapter/components/button/mdc-button.vue
 @ ./node_modules/vue-mdc-adapter/components/button/mdc-button.vue
 @ ./node_modules/vue-mdc-adapter/components/button/index.js
 @ ./node_modules/vue-mdc-adapter/components/index.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

After much research and googling I've realized the problem is the spread operator is the problem and I've tried about everything I can as far as babel plugins to fix it. However, I've been completely unsuccessful. At the moment I've got a .babelrc that has all sorts of stuff I likely don't need in an effort to get this to work:

```
{
  "presets" : [
    "es2015", "stage-3"
  ],
  "plugins": [
	"transform-es2015-destructuring",
	"transform-object-rest-spread",
	"syntax-object-rest-spread",
	"transform-object-assign",
	"transform-es2015-parameters"
  ]
}
```

Any help or suggestions would be most welcome.

**Comment by griest024** [comment]
Have you tried using `babel-preset-env`? It's recommended by Babel.

**Comment by coogle** [comment]
I just tried it and it has the same result unfortunately. I've tried 
many different plugins trying to get this project to work because I 
really want to use it but I've been stuck on this issue for quite a 
while now. Any other ideas? I assume you use webpack / babel so 
certainly you must have something different in your config than mine.

**Comment by griest024** [comment]
Try importing `vue-mdc-adapter/dist`

**Comment by coogle** [comment]
That did it! But why?

**Comment by griest024** [comment]
The `dist` folder holds the precompiled versions of the components. I'm not sure why Babel couldn't compile it for you but that's something funky with your own environment, not this library.

**Comment by coogle** [comment]
Thanks for the help!

**Comment by stasson** [comment]
@coogle 

Your babel config looks good. Although preset es2015 is a obsolete and it's probably better to use preset env with latest babel:

- This is the minimal config i'd use for webpack + vue + vue-router + vue-mdc-adapter
```javascript
{
   ["env", { "modules": false }]
  "plugins": [
    "transform-object-rest-spread",   
    "syntax-dynamic-import"
  ],
  "presets": [
  ],
}
``` 

- The problem is most probably that code in node_modules do not get transpiled in your webpack config: vue-mdc-adapter and @material source distribution is es6 and need to be transpiled in order to build from source. It's missing from the [doc](https://github.com/stasson/vue-mdc-adapter/blob/master/docs/getting-started.md#building-from-es6-sources)

```javascript
// babel loader config
  {
    test: /\.js$/,
    loader: 'babel-loader',
    include: [
      path.resolve(__dirname, 'node_modules/@material')
      path.resolve(__dirname, 'node_modules/vue-mdc-adapter')
    ]
  }
```
Note you do that only if you want to build for source. 

As @griest024  said, You can [build using the pre-built distribution](https://github.com/stasson/vue-mdc-adapter/blob/master/docs/getting-started.md#using-the-umd-distribution).  This is probably the easiest.

I fix the doc...

**Comment by stasson** [comment]
in next release, new ESM distribution will be transpiled so it should work seemlessly with webpack ...
