### ISSUE TITLE
Fab Custom Icons Don't work

### ISSUE THREAD

**Issue by coogle** [stasson/vue-mdc-adapter#150]
Hello,

FAB custom icons don't work:

Take, for example:

```
<mdc-fab fixed class="mdi mdi-account mdi-24px" href="@route('agent.clients.create')" v-show="currentTab == 'active'"></mdc-fab>
```

This results in HTML where the class for the icon being used is attached to the `<a>` tag, while inside of that `<a>` tag is a `<span class="mdc-fab__icon"></span>`. The icon class therefore does not display as the icon classes provided need to attach to the `<span>` not `<a>` tag to be rendered, for example:

```
    <a href="@route('agent.clients.create')" class="mdc-fab mdc-fab--fixed mdc-ripple-upgraded" style="--mdc-ripple-fg-size:33.6px; --mdc-ripple-fg-scale:2.65464;">
    <i class="mdi mdi-account-plus mdi-36px mdc-fab__icon"></i>
    </a>
```

**Comment by stasson** [comment]
not ideal for the markup, but you can get it work like this:

https://codepen.io/stasson/pen/KyLQyR

**Comment by coogle** [comment]
Good to know, but at the very least then the documentation is out of date:

https://stasson.github.io/vue-mdc-adapter/#/component/fab

**Comment by stasson** [comment]
yes. the doc is out of date.  And the rendered markup is not ideal. 
Guess I need to fix both.
Thanks for the catch anyway.

**Comment by stasson** [comment]
need to fix icon-toggle as well :(

**Comment by coogle** [comment]
I’d be happy to contribute more but I haven’t figured out how to build this
module from source yet for my project!
