### ISSUE TITLE
Should mdc-radio's checked prop be set from the v-model?

### ISSUE THREAD

**Issue by pgbross** [stasson/vue-mdc-adapter#155]
If I have one or more radio buttons with a `v-model` specified, it would seem to be more useful if the checked status was set initially by the `v-model` as well as for the `v-model` to track the radio's value.

For example:
```
<mdc-radio v-model="downloadFormat" label="json" />
```
seems more intuitive than what is currently needed

```
<mdc-radio v-model="downloadFormat" label="json" :checked="downloadFormat==='json'">
```

In the `mdc-radio.vue` code the model is set to have a prop of "picked" which is unused. Naively it would be possible to remove "checked" from the props object and replace with "picked". Then in the `mounted()` method it could set "checked" using the current `v-model` and the `value|label`.

e.g. (again super primitively)
```
this.checked = (this.value ? this.value : this.label) === this.picked;
```

It may also be helpful to add a `watch` on the `picked` prop, so that programatic updates to the `v-model` are reflected in the UI.

cheers,
--philip

**Comment by stasson** [comment]
@pgbross 

Agreed, I'll keep the checked prop. But if not set, will check as per v-model value
