### ISSUE TITLE
fix(layout-grid): `mdc-layout-grid-inner` should be a standalone component

### ISSUE THREAD

**Issue by rustemgareev** [stasson/vue-mdc-adapter#161]
Currently `mdc-layout-grid-inner` is hard coded into `mdc-layout-grid` therefore it's not flexible for reuse in layout when needed. Additionally, current naming `mdc-layout-inner-grid` doesn't look intuitively regarding to `mdc-layout-grid__inner` CSS class, so it's worth considering name it as `mdc-layout-grid-inner`.

**Comment by stasson** [comment]
I understand the point about the name, not the point about _hard coded into `mdc-layout-grid`_

**Comment by rustemgareev** [comment]
I meant hard-coded, written without ability for re-use.

**Comment by rustemgareev** [comment]
https://github.com/stasson/vue-mdc-adapter/blob/master/components/layout-grid/mdc-layout-grid.vue#L3

**Comment by rustemgareev** [comment]
I should reword: `mdc-layout-grid-inner` hard-coded into `mdc-layout-grid` makes it hard to use
`mdc-layout-grid` only, without cells.

```html
<mdc-layout-grid>
  Layout grid used only for setting the width of inner content!
  Hard-coded `mdc-layout-grid-inner` makes it impossible to use it this way!
</mdc-layout-grid>
```

**Comment by stasson** [comment]
won't fix as per discussion...
