### ISSUE TITLE
fix(components): components should follow MDC-Web naming convention

### ISSUE THREAD

**Issue by rustemgareev** [stasson/vue-mdc-adapter#162]
There is a lot of mismatching in Vue-MDC-Adapter component names with MDC-Web's components class names.

For instance, Vue-MDC-Adapter uses [`mdc-layout-cell`](https://github.com/stasson/vue-mdc-adapter/blob/master/components/layout-grid/mdc-layout-cell.vue) while MDC-Web actually uses `mdc-layout-grid-cell` (["mdc-layout-grid__cell" class](https://github.com/material-components/material-components-web/blob/master/packages/mdc-layout-grid/mdc-layout-grid.scss#L48)). VMA uses [`mdc-card-header`](https://github.com/stasson/vue-mdc-adapter/blob/master/components/card/mdc-card-header.vue) while MDC-Web actually uses `mdc-card-primary` (["mdc-card__primary"](https://github.com/material-components/material-components-web/blob/master/packages/mdc-card/mdc-card.scss#L34)). Also: `mdc-card-text` vs. `mdc-card-supporting-text`, `mdc-card-action-button` vs. `mdc-card-action`. It's worth to create a separate issue for each component with mismatching name.

It makes hard to assume what to use intuitively when people are coming from MDC-Web documentation.

**Comment by stasson** [comment]
outdated
