### ISSUE TITLE
Ability to have button beside textbox?

### ISSUE THREAD

**Issue by kewlniss** [stasson/vue-mdc-adapter#166]
I was using MDC-Web directly and had the following markup:

>     <div class="mdc-text-field" data-mdc-auto-init="MDCTextField">
>         <input id="search" type="textarea" class="mdc-text-field__input" />
>         <label for="search" class="mdc-text-field__label">Search</label>
>         <div class="mdc-text-field__bottom-line"></div>
>     </div>
>     <button type="submit" class="mdc-button mdc-button--raised mdc-ripple-surface" data-mdc-auto-init="MDCRipple">Search</button>
> 

I've started converting the site over to utilize the adapter and changed the code to:

`<mdc-textfield v-model="search" label="Search" /><mdc-button raised>Search</mdc-button>`

What would I need to do in order to keep the textfield and the button on the same line?

I can utilize the mdc-layout-grid, but it adds a lot of markup and the alignment is off:

`<mdc-layout-grid>
    <mdc-layout-cell><mdc-textfield v-model="search" label="Search" /></mdc-layout-cell>
    <mdc-layout-cell align="middle"><mdc-button raised>Search</mdc-button></mdc-layout-cell>
</mdc-layout-grid>`

Any suggestions to what I can do differently?

**Comment by griest024** [comment]
@kewlniss You're not doing anything wrong, you don't need to use a `layout-grid`. It requires changes to the library.

**Comment by griest024** [comment]
@stasson I think we need to add before and after slots to `mdc-textfield` and possibly in between the field and the helptext. In order to format this correctly, the button needs to be inside `mdc-textfield-wrapper`

**Comment by rustemgareev** [comment]
If you're okay without floating label, try this simple approach:
Wrap text-field and button into flexbox div, Add `fullwidth` prop to the text-field, and make text-field height of 36px (to make it equal with button):

```html
<template>
  <div class="my-search-box">
    <mdc-textfield v-model="search" label="Search" fullwidth></mdc-textfield>
    <mdc-button raised>Search</mdc-button>
  </div>
</template>

<style lang="scss">
.my-search-box {
  display: flex;
  align-items: center;
}

.my-search-box .mdc-text-field--fullwidth {
  height: 36px;
}
</style>
```

**Comment by stasson** [comment]
@kewlniss 

Sorry got out of touch for a while ...

I'm not sure adding start/end slot is the way to go here ... The issue here is that I wrapped markup in a display:block div. Where I should have a aligned to mdc's original style (display:inline-block) 
Unfortunately, the refactoring is not as straight forward as I'd like (the display style can vary  depending on the type of textfield...) It may take some time to get a proper fix.

In the mean time, the best for you would be to just add a class to force display:inline-block
<https://codepen.io/stasson/pen/wpgGxa>

**Comment by kewlniss** [comment]
Perfect, thanks guys!
