### ISSUE TITLE
IE 11 - Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by kewlniss** [stasson/vue-mdc-adapter#168]
Several places in the code the .includes method is used. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

Unfortunately, IE 11 doesn't support this method, so a polyfill needs to be used.

If indexOf can be used instead, that would be ideal, but if this a 'won't fix' type of issue, then the documentation should be updated to let developers know of the limitation and to utilize the polyfill mentioned in the reference above to get it to work in IE11.

**Comment by stasson** [comment]
Thanks for letting me know. 
library should have same support as MDC Web. IE11  included.
need to figure out the best way to fo it ...

**Comment by stasson** [comment]
Not sure why my babel config is not adding polyfills !?!

will investigate

**Comment by griest024** [comment]
@stasson you can assign this to me if you want

**Comment by griest024** [comment]
@stasson [babel does not recommend adding the polyfill to libraries.](https://babeljs.io/docs/usage/polyfill/) Are you sure that's what you want to do?

**Comment by stasson** [comment]
no I'm not sure. IE11 support much more complex than what I thought:
- there is the polyfills/transform runtime issue
- there is the autoprefixer issues: looks like my build config is degrading orginal MDCWeb css !?! for example I can't get persitent drawer to show up in IE11...

Well that's a complex issue. I guess i'll start a dev branch for ie11 support

**Comment by griest024** [comment]
@stasson a separate branch is probably a good idea. There is definitely something funky happening with IE11, because my whole computer freezes when I run the demo page in IE11.

**Comment by stasson** [comment]
I'm struggling here. obviously adding babel pollyfill will do the trick. now it is a rather big pollyfill, not really optimized ...

**Comment by kewlniss** [comment]
@stasson I'm not sure if there are more issues for IE11 compatibility, but if the main issue is the .includes then it may just be worth adding this polyfill directly to the library (and not rely on babel's larger polyfill):

    if (!String.prototype.includes) {
        String.prototype.includes = function(search, start) {
            'use strict';
            if (typeof start !== 'number') {
                start = 0;
             }    

             if (start + search.length > this.length) {
                 return false;
            } else {
                return this.indexOf(search, start) !== -1;
           }
        };
    }

That was taken from the link I originally posted.

**Comment by stasson** [comment]
@kewlniss 

did more tests today:

actually there are to polyfill needed today:
- Object.assign
- Array.prototype.includes   (not string includes)

In next release I'll be using babel Object.assign transform, and I'll rewrite the code using indexOf vs includes. So we won't need polyfills anymore.

That being said there is other issues with css and I'm not sure I'll be able to fix them for next release...

**Comment by mmunchandersen** [comment]
@stasson using /*! Raygun4js - v2.12.0 - 2018-08-28 I still get this error in IE 11 on 18-sept-2018
