### ISSUE TITLE
Possible support for @blur on fields like select and input?

### ISSUE THREAD

**Issue by kewlniss** [stasson/vue-mdc-adapter#172]
I may be missing something obvious, but I'm trying to get a function kicked off from the blur event on an text field and select field. 

    <mdc-textfield v-model="otherdata" label="Other Data" @blur="notifyDataChanged(otherdata)" />

If I add the @blur to a MDC-Web input field, it gets kicked off.

But adding it to the Vue MDC Adapter fields brings no joy. 

I suspect it is because it doesn't actually make it to the input field itself.

**Comment by griest024** [comment]
Yes the `mdc-textfield-wrapper` is causing some issues.

@stasson I think we should just manually emit the `blur` event.

**Comment by griest024** [comment]
@kewlniss Can you paste the code you are using with MDC Web to capture the `blur` event?

**Comment by stasson** [comment]
@kewlniss  blur doesn't bubble, but focusout does. you want to add a native event listener to a component so you need to add the .native modifier:  `@focusout.native="handler"` 
You may want to do something like that until there is support for @blur in the library: <https://codepen.io/stasson/pen/mpWRNr> 


@griest024 and @kewlniss 
Adding custom-event support for focus-out  is in the spirit. 
- which components ?
only textfield and select ?
- do we only need `blur` 
any obvious case where we would need `focus` ?

**Comment by kewlniss** [comment]
The @focusout.native is meeting my needs for now, so thank you for the work around!

**Comment by kewlniss** [comment]
Thanks for getting this to work on the textfield. Unfortunately, the select still requirs the @focusout.native approach. Any chance this can be re-opened and have the select addressed as well?

Great work on this adapter by the way!
