### ISSUE TITLE
MDC Theme documentation *how to* does not help when trying to set theme

### ISSUE THREAD

**Issue by jan-johansson-mr** [stasson/vue-mdc-adapter#178]
Hi,

Most of the documentation is excellent, but I think it is confusing when it comes to setting the MDC theme.

I followed the instructions of setting up the Vue solution and it works out of the box, which is great!

My next step was to theme MDC, and found the instructions on the "Get Started" at [Getting Started](https://stasson.github.io/vue-mdc-adapter/#/docs/getting-started), at the section "Create your own SASS Theme".

The documentation says that we need a sass-loader (no sass-loader is included in the given webpack template (referred to in the "Get Started" section), looking at the package.json). My immediate though was "What sass-loader should we use?". The next step after installing a sass-loader (and it's dependency on node-sass), comes the configuration. Here again it's unclear how to set it up. It is mentioned in the "Get Started" to configure webpack with a snippet. The snippet is taken from the following file [webpack.config.js (stasson/vue-mdc-adapter)](https://github.com/stasson/vue-mdc-adapter/blob/master/webpack.config.js), but this file is very different from the setup given by the Vue webpack template (the webpack config is split into files in the build folder). So where should the configuration go? The snippet given is aligned with the given webpack.config.js file, so it is unclear how it should be in the template environment.

The documentation give an example of "theme.scss", which is great! But it is unclear where the file should be created in the solution.

I have not been able to theme MDC yet, but I hope for some assistance on how to configure correctly.

Thanks!

**Comment by griest024** [comment]
@jan-johansson-mr The build process for the boilerplate has a lot of logic in it.  You might want to start with a clean webpack config to get the SASS theming working.

The general process for theming is:

1. Define all the variables *before* you import the styles:
```sass
// theme.sass
$mdc-theme-primary: rgba(82, 31, 206, 0.62)

@import "vue-mdc-adapter/components/styles"
```

2. Load `theme.sass` somehow, probably in your Vue entrypoint:
```vue
<!-- App.vue -->
<style lang="sass" src="./assets/theme.sass"></style>
```

3. If you are using webpack (you probably should be), then configure webpack to use `sass-loader`. This project itself is a good guideline on how to configure it.
3a. Define your style loaders (note `sass-loader` is the important one here):
```js
const cssLoaders = [
  {
    loader: 'css-loader',
    options: {
      sourceMap: false,
      'import': false,
    },
  },
  {
    loader: 'postcss-loader',
    options: {
      sourceMap: false,
      plugins: () => [require('autoprefixer')({grid: false})],
    },
  },
  {
    loader: 'sass-loader',
    options: {
      sourceMap: false,
      includePaths: [path.resolve(__dirname,'./node_modules')],
    },
  },
];
```
 3b. Configure the vue loader to use these loaders for loading styles:


```js
{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: { 
    loaders:  ['vue-style-loader'].concat(cssLoaders), 
  }
}
```

**Comment by jan-johansson-mr** [comment]
Thank you,

But again, what you write reflects the instructions already. It does not bring new information to the table, if you like. E.g. there is not webpack.config.js any more in the Vue starter template (vue init webpack my-project or vue init webpack-simple my-project). There is a number of files in the build folder, that takes care of the configuration.

I think it is nice with instructions that aligns with what you get from a 'vue init...'.

I dug deeper into the issue a few hours ago, but I'm still stuck :-(

Thanks

**Comment by jan-johansson-mr** [comment]
Hi,

I finally got it to work :-)

Looking into the build folder of the created solution (from "vue init webpack my-project"), there is a "utils.js" file. There is a function generating loaders, called "generateLoaders":

```
  // generate loader string to be used with extract text plugin
  function generateLoaders (loader, loaderOptions) {
    const loaders = [cssLoader]
    if (loader) {
      loaders.push({
        loader: loader + '-loader',
        options: Object.assign({}, loaderOptions, {
          sourceMap: options.sourceMap
        })
      })
    }

    // Extract CSS when that option is specified
    // (which is the case during production build)
    if (options.extract) {
      return ExtractTextPlugin.extract({
        use: loaders,
        fallback: 'vue-style-loader'
      })
    } else {
      return ['vue-style-loader'].concat(loaders)
    }
  }

  // https://vue-loader.vuejs.org/en/configurations/extract-css.html
  return {
    css: generateLoaders(),
    postcss: generateLoaders(),
    less: generateLoaders('less'),
    sass: generateLoaders('sass', { indentedSyntax: true }),
    scss: generateLoaders('sass'),
    stylus: generateLoaders('stylus'),
    styl: generateLoaders('stylus')
  }
```
At the end of the function, there is a generator for "sass", but without any options. I'lve included the option given by the comments here in this section (corresponding to the documentation). The modified code becomes:

```
  function generateLoaders (loader, loaderOptions) {
    const loaders = [cssLoader]
    if (loader) {
      loaders.push({
        loader: loader + '-loader',
        options: Object.assign({}, loaderOptions, {
          sourceMap: options.sourceMap
        })
      })
    }

    // Extract CSS when that option is specified
    // (which is the case during production build)
    if (options.extract) {
      return ExtractTextPlugin.extract({
        use: loaders,
        fallback: 'vue-style-loader'
      })
    } else {
      return ['vue-style-loader'].concat(loaders)
    }
  }

  // https://vue-loader.vuejs.org/en/configurations/extract-css.html
  return {
    css: generateLoaders(),
    postcss: generateLoaders(),
    less: generateLoaders('less'),
    sass: generateLoaders('sass', { indentedSyntax: true }),
    scss: generateLoaders('sass', { includePaths: [path.resolve(__dirname,'../node_modules')]}),
    stylus: generateLoaders('stylus'),
    styl: generateLoaders('stylus')
  }

```
With the added "includePahts" at the end. However, the path is resolved to where the function is executed, hence the path must be taken with care (brittle solution).

The change enables the usage of MDC theme. This solution is only applicable to 'vue init webpack ...' template. The 'vue init webpack-simple ...' has another structure (without the 'build' folder).

Thanks

**Comment by griest024** [comment]
Glad you got it working.

Either way, this is not an issue with this library. If you need to, open an issue in the repos for the templates.

**Comment by stasson** [comment]
re-opening the issue just to keep track that doc is not explicit enough. 
probably need to add a link to https://github.com/stasson/vue-mdc-adapter-template or fork the real vue webpack template.

**Comment by stasson** [comment]
@jan-johansson-mr 

Well yes `@import ~@material` wont work because MDCWeb sass files also assume node-modules as root path.

**Comment by stasson** [comment]
ok

I have forked vue-cli webpack template and added support for theme.scss

[stasson/vue-mdc-adapter-webpack](https://github.com/stasson/vue-mdc-adapter-webpack)

will add notes to readme and getting started

**Comment by henrychavez** [comment]
hi @stasson I'm having this error:

Module build failed:
undefined
            ^
      No mixin named mdc-states

I just create the project and run: `npm run dev` I notice that the config files are the same as` stasson/vue-mdc-adapter-webpack` can u help me? I think the problems is that the modules with @material aren't found

**Comment by griest024** [comment]
Did you install `@material`?

**Comment by henrychavez** [comment]
@griest024 yes! I solve the problem, the template install the version 0.26.0 of material components but the styles are using a mixin from the latest version 0.28.0 I just install the latest version "material-components-web": "0.28.0"
