### ISSUE TITLE
refactor(checkbox): checkbox's label should be a slot

### ISSUE THREAD

**Issue by rustemgareev** [stasson/vue-mdc-adapter#185]
Currently we set label for the checkbox with a prop, but it makes impossible to use anchor links in the label text (e. g., "I agree with the <a href="#">Terms of Service</a>").

**Comment by stasson** [comment]
@rustemgareev 

I tried to get label as a slot and and put "I agree with the <a href="#">Terms of Service</a>". it does look very bad. I'm not sure MDCWeb markup is supposed to be used like that.

plus another issue is that label click's are captured to switch state and do ripple...

I guess it'd be easier to do 

```html
<mdc-checkbox/> <span>I agree with the <a href="#">Terms of Service</a><span>
```

umless you see another way with the MDC Markup ?

**Comment by rustemgareev** [comment]
@stasson [Current implementation of the checkbox](https://github.com/stasson/vue-mdc-adapter/blob/master/components/checkbox/mdc-checkbox.vue) uses `mdc-form-field` as a wrapper, so there is no difference with [MDC-Web's usage of checkbox and label together] - label sits as a checkbox' sibling inside an `mdc-form-field`. I tried to use anchor in this markup - it looks and behaves fine.

**Comment by stasson** [comment]
@rustemgareev  

ok plz send me a MDCWeb javascript (autoinit) codepen with your markup, and I'll check what I got wrong.
