### ISSUE TITLE
Select with pre-selected option doesn't float label

### ISSUE THREAD

**Issue by pgbross** [stasson/vue-mdc-adapter#188]
### What vue-mdc-adapter Version?
0.7.3

### What are the steps to reproduce the bug?
1. Set property `mode = 'all'` (or any valid option).
2. Render an mdc-select (mdc-menu-select version)

```
<mdc-select v-model="mode"  label="Task mode">
    <mdc-option value="sequential">Sequential</mdc-option>
     <mdc-option value="all">All</mdc-option>
</mdc-select>
```

3. The select does not float the label.

### What is the expected behavior?
When there is a pre-selected option the label should float.

### What is the actual behavior?
During the adapter initialization it checks to see if the value of the property is an optionValue and calls the foundation setSelectedIndex, but the foundation does not float the label (see issue [https://github.com/material-components/material-components-web/issues/1810](https://github.com/material-components/material-components-web/issues/1810)).

### Any other information you believe would be useful?

Similarly to text field, the recommendation appears to be that the html created should set the class to float the label as necessary. They also think it should be done by the foundation in the future.

One possible place this could be done in `mdc-menu-select.vue` is in the initialization.

```
foundation.init()
let options = this.$refs.menu.items
for (let i = 0; i < options.length; i++) {
   let optionValue = options[i].getAttribute('data-value') || options[i].textContent.trim()
    if (this.value === optionValue) {
       foundation.setSelectedIndex(i)
       this.$set(this.labelClasses, 'mdc-select__label--float-above', true); // <--- added line
       break;
    }
}
```

This would appear to be safe even if the foundation is eventually updated to float the label itself as part of the setSelectedIndex() method.

**Comment by stasson** [comment]
@pgbross 
thanks a lot for the catch and the quality of the issue description !
