### ISSUE TITLE
Ensure ripple mixin component instance member does not conflict

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#204]
[`this.ripple`](https://github.com/stasson/vue-mdc-adapter/blob/40a03ce2a1f3abf7f3fa3646b028ef9939fa7220/components/ripple/mdc-ripple-base.js#L70) might conflict with user defined fields on the component instance. I think it would be a good idea to rename the field to `__vueMDC__ripple` or something similar. It might be a good idea to use this prefix anytime the library sets a field on a user component instance.

**Comment by stasson** [comment]
outdated
