### ISSUE TITLE
Type atribute missing in mdc-textfield's rendered input element

### ISSUE THREAD

**Issue by pgbross** [stasson/vue-mdc-adapter#210]
### What vue-mdc-adapter Version?
0.8.0

### What are the steps to reproduce the bug?
1. Set attribute `type = 'password'`on textfield.

```
<mdc-textfield label="Password" v-model="password" type="password" autocomplete="password"></mdc-textfield>
```

3. When rendered the `<input/>` element has no type

### What is the expected behavior?
The input element should use the type="password" to render a password style input.

### What is the actual behavior?
The type attribute is missing.

### Any other information you believe would be useful?

After the refactor for MDC 0.28 it seems as if there is a missing `:type="type"` in the markup defined in `mdc-textfield.vue` for the `custom-element`.

**Comment by stasson** [comment]
@pgbross 

sorry about that. I'll release a fix asap
