### ISSUE TITLE
mdc-textfield: model binding issue

### ISSUE THREAD

**Issue by RobertSmits** [stasson/vue-mdc-adapter#215]
The multirow textfield has an issue where the input gets placed in the model, but the content from the model gets not placed in the textfield.
This bug can be seen even on the demo page.
If you start typing in one of the single line textfields the others follow but the multiline textfield only gets the floating label. 
Same when a default text is placed in the model.

To continue this issue:
If you click on the second textfield (outlined) the two others (box and fullwidth) still update but the previous (normal) doesn't update.

This issue is present on the current master 
 915a21eb80358d2b1168aaa73b692b9cf30fe462

**Comment by RobertSmits** [comment]
I kind of fixed it by replacing the custom-element with v-if / v-else to a textarea or input.
I don't think this is the most elegant solution but I'm a vue noob and don't really see the real issue with the custom-element. 
For this reason i will not yet create a pull request.

Feel free to create a better fix or ask for the PR.

**Comment by stasson** [comment]
Thx, will fix his asap

**Comment by stasson** [comment]
@RobertSmits 

Thanks a lot for catching the issue and for the branch.
I didn't merge your branch but inspired from it for the fix.

Actually I do not fully understand the bug myself, I guess It has to do with the vue v-model internals teaxtarea  which I may have broken, wraping it up in a custom element. I'll try to find the time to understand it.

thxs anyway
