### ISSUE TITLE
mdc-select: wrong menu height calcultaion

### ISSUE THREAD

**Issue by RobertSmits** [stasson/vue-mdc-adapter#220]
### Short

The height and offsetHeight in the mdc-select menu return `0` resulting in wrong styling of the menu.
The menu should open with the selected item on the same level as the select component.
A long menu also falls off screen because of this.

How it is: 
![screenshot from 2018-01-20 16-21-43](https://user-images.githubusercontent.com/6593428/35185049-17a82026-fdfe-11e7-9cdb-560a43eefc12.png)

How it should be:
![screenshot from 2018-01-20 16-21-50](https://user-images.githubusercontent.com/6593428/35185050-17be9e64-fdfe-11e7-83f2-180c4194504e.png)

### Long

foundation.js@248
```
    this.adapter_.setMenuElStyle('display', 'block');
    const menuHeight = this.adapter_.getMenuElOffsetHeight();
    const itemOffsetTop = this.adapter_.getOffsetTopForOptionAtIndex(index);
    this.adapter_.setMenuElStyle('display', '');
```

mdc-menu-select.vue@102
```
setMenuElStyle: (propertyName, value) => 
        this.$set(this.menuStyles, propertyName, value), 
```
On the first line in foundation.js the menu style is set to `display: block`.
The DOM update from reactive properties happens async, although the foundation relies on this update happening immediate.
So when we get to the 2nd and 3rd line the display property is still set to `none` resulting in a wrong height and further resulting in wrong styling.

**Comment by stasson** [comment]
Good catch ! 
Thxs a lot
