### ISSUE TITLE
mdc-menu cropped if inside an anchor

### ISSUE THREAD

**Issue by gaspaonrocks** [stasson/vue-mdc-adapter#228]
In the docs it is said to use that template : 
```html
<mdc-menu-anchor>
  <mdc-button>Menu</mdc-button>
  <mdc-menu >
    <!-- ... -->
  </mdc-menu>
</mdc-menu-anchor>
```
yet if I do that the do not show up entirely. I have to only wrap the element that pops up the menu for it to display.

I should also add that my menu is in a toolbar so I don't know if it has an impact

**Comment by stasson** [comment]
@gaspaonrocks 

Can you send a codepen or example and also which OS/Browser you are using ?

**Comment by gaspaonrocks** [comment]
@stasson 

I'm using Chrome but it seems I cannot reproduce it in a codepen... So I'm closing this issue...

Sorry for the inconvenience and thanks for the amazing work !
