### ISSUE TITLE
mdc-textfield: move class vars from data to computed

### ISSUE THREAD

**Issue by getriebesand** [stasson/vue-mdc-adapter#231]
I need to change helptextValidation programmatically. But this doesn't work because helpClasses will be created once on render.
Can you please move vars with props dependencies to computed?

**Comment by stasson** [comment]
yes

**Comment by alxpez** [comment]
Hi @stasson, I've noticed the same issue on other components, once rendered they don't display the changes to their props:

- mdc-switch (align-end)
- mdc-list (any: dense, bordered, avatar-list, two-line)
- mdc-select (disabled)

I could open a issue for each of them if it's more convenient (I haven't check all the components/props).
Thanks for this project though, great work!

**Comment by stasson** [comment]
@alxpez 

thanks a lot for letting me know. I'll fix those in next release. 
I'll close this one. if you find others, better to open new issue.
