### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by tarreislam** [stasson/vue-mdc-adapter#232]
Hello.

So I decided to check this out but I am having problem re-creating one of the [examples shown in the documentation](https://stasson.github.io/vue-mdc-adapter/#/component/layout-app). 

The documentation states that:
> `mdc-layout-app` is a flexible layout component for properly positioning the toolbar, drawer and main content.

But [this](https://i.imgur.com/sUTRGEX.png) and [this](https://i.imgur.com/UMN13Aw.png) is the result I get. 

The vue project was created using `vue init webpack` 

This is how my template looks like

```
<template>
    <div>
        <mdc-layout-app>
            <mdc-toolbar slot="toolbar" fixed>
                <mdc-toolbar-row>
                    <mdc-toolbar-section align-start>
                        <mdc-toolbar-menu-icon event="toggle-drawer"></mdc-toolbar-menu-icon>
                        <mdc-toolbar-title>abc</mdc-toolbar-title>
                    </mdc-toolbar-section>
                </mdc-toolbar-row>
            </mdc-toolbar>
            <mdc-drawer slot="drawer" toggle-on="toggle-drawer">
                <mdc-drawer-list>
                    <mdc-drawer-item start-icon="inbox">a</mdc-drawer-item>
                    <mdc-drawer-item start-icon="warning">b</mdc-drawer-item>
                    <mdc-drawer-item start-icon="build">c</mdc-drawer-item>
                </mdc-drawer-list>
            </mdc-drawer>
            <main>
                <mdc-card>
                    <mdc-card-header title="title" subtitle="subtitle"/>
                    <mdc-card-text> abc</mdc-card-text>
                    <mdc-card-actions>
                        <mdc-card-action-button>Action</mdc-card-action-button>
                    </mdc-card-actions>
                </mdc-card>
            </main>
        </mdc-layout-app>
    </div>
</template>
```
I can kinda fix the problem by adding `float:left` to the `mdc-drawer` tag.

Package.json
```
"material-components-web": "^0.29.0"
"vue-mdc-adapter": "^0.9.0"
```

**Comment by tarreislam** [comment]
Hmm. I think I get it. I need to create the classes `mdc-layout-app--* ?

**Comment by stasson** [comment]
@tarreislam 

you do not need to create the classes. 
did you import vue-mdc-adapter styles in your?

you can import default theme
```
import  "vue-mdc-adapter/dist/vue-mdc-adapter.css";
``` 

or [create your own theme with sass](https://github.com/stasson/vue-mdc-adapter/blob/master/docs/getting-started.md#create-your-own-sass-theme)

**Comment by tarreislam** [comment]
Whops. I was only including `"material-components-web/dist/material-components-web.css`. This solved the issue. 

Thank you stasson!
