### ISSUE TITLE
mdc-snackbar does not display actionButton

### ISSUE THREAD

**Issue by alxpez** [stasson/vue-mdc-adapter#234]
I've encountered (what it seem to me as) an odd behaviour with the snackbar:

This snackbar,

      <mdc-snackbar />

(it's placed on the main component at the top-most index)
I open it with the following options:

    vm.$root.$emit('show-snackbar', {
      message: 'Open GitHub',
      actionText: 'Go',
      actionHandler: function () {
        window.open('https://github.com/', '_blank')
      }
    })

It displays correctly the first time, but if I press the actionButton, the next time the snackbar gets displayed the actionButton is hidden (literally it has aria-hidden="true") and the snackbar does not hide after the timeout (it persists of forever without a button).

If I don't press the actionButton, and it hides naturally after the timeout, there's no problem (and if it gets displayed again the button is shown), so I understand that must be related to the actionButton interaction.

Just in case, I tried setting "dismisses-on-action" to false, but I get same results.

      <mdc-snackbar :dismisses-on-action="false"/>

Tested in chrome, firefox and safari (last versions) for macOS

**Comment by stasson** [comment]
@alxpez 

My guess is there's a kind of a bug in MDCSnackbarFoundation. 

I have tried to do the open async : 
```javascript 
          this.$nextTick( () =>
            window.open('https://github.com/', '_blank') )
```
seems less reproducible, but still there

I'll try to reproduce with pure MDCWeb and raise an issue to material-components...

**Comment by pgbross** [comment]
I have reproduced this bug in `material-components-web` and after investigation I do not believe there is a work around in `vue-mdc-adapter`.
I have raised an [issue](https://github.com/material-components/material-components-web/issues/2545) where you may follow the MDC team's response and watch for any fixes.
