### ISSUE TITLE
"No mixin named mdc-states" compile error

### ISSUE THREAD

**Issue by thotze** [stasson/vue-mdc-adapter#237]
I keep on getting an install error on Windows - first with fsevents (which happens since fsevents doesn't work on Windows and I think is optional for vue-cli), but after that, with mdc-states.

Each time, I get a compile error:

"error in ./src/theme.scss

Module build failed: 
Undefined
                   ^
        No mixin named mdc-states"

Following that, there's a backtrace.  Just trying to get through that particular rabbit hole, I went through and deleted the first couple locations it mentions to see if I could get the package to compile, but so far, no luck.

**Comment by Xintium** [comment]
I fixed it by manually go into package.json and update material-components-web to the latest verison

**Comment by thotze** [comment]
thanks - that worked! Changing the line in package.json to

...
  "dependencies": {
    "material-components-web": "^0.29.0",
...

did the trick.

**Comment by griest024** [comment]
Was it warning you about peer dependencies when you installed npm dependencies?

**Comment by stasson** [comment]
@thotze  
I guess I can close this one ?
plz re-open if you still have issues
