### ISSUE TITLE
mdc-textfiled: pass event-listeners to input element

### ISSUE THREAD

**Issue by getriebesand** [stasson/vue-mdc-adapter#242]
I need to bind a keyup listener to the input field.
Can you pass all event listeners to input element?
mayby change:
```
        @input="updateValue($event.target.value)"
```
to:
```
v-on="$listeners"
```
https://vuejs.org/v2/api/#vm-listeners

I'm not sure if this is the right way to do that.

**Comment by stasson** [comment]
sounds a good idea for input elements. will check ...
