### ISSUE TITLE
mdc-textfield outline and fullwidth

### ISSUE THREAD

**Issue by tarreislam** [stasson/vue-mdc-adapter#243]
Salutations

Mixing `fullwidth` and `outline ` in `mdc-textfield` will cause the field to be "disabled".
```
 <mdc-textfield
 fullwidth
 outline
 label="label"/>
```

/

**Comment by stasson** [comment]
Outline style is pretty new. need to check if MDCWeb supports it or if ther is any plan...

**Comment by stasson** [comment]
@tarreislam 

as of today, outline and full width can not be used together.
I'll add a fix or workarround...

**Comment by stasson** [comment]
@tarreislam  see ref https://material.io/components/web/catalog/input-controls/text-field/#full-width
