### ISSUE TITLE
mdc-textfield and multiline disabled scrolling. Bug or intended?

### ISSUE THREAD

**Issue by tarreislam** [stasson/vue-mdc-adapter#244]
Hello!

When you set a long text multiline `mdc-textfield` to `disabled`, The scrolling do not work. I do not know if this is intended or not, but this is not the case for the regular `textarea` tag

recreate:
```
 <mdc-textfield
 fullwidth
 disabled
 :value="new Array(999).join('####')"
 label="label"/>
```

**Comment by stasson** [comment]
@tarreislam 

I guess it's what MDCWeb does. need to check

**Comment by stasson** [comment]
seems to be same behavior in MDCWeb. will ask the question to MDCWebTeam

**Comment by stasson** [comment]
see ref:   https://material-components-web.appspot.com/text-field.html

**Comment by stasson** [comment]
@next #506
