### ISSUE TITLE
mdc-list-item does not support click event

### ISSUE THREAD

**Issue by neclepsio** [stasson/vue-mdc-adapter#246]
I think mdc-list-item should support click event.

Maybe something like `<li class="mdc-list-item" v-on="$listeners">` is even a better alternative.

**Comment by stasson** [comment]
ok for @click. 
v-on="$listeners need to investigate...

**Comment by daneren2005** [comment]
@neclepsio Did you find an alternative for this?  I'm new to this project but a non-clickable list item seems kind of pointless :D

**Comment by stasson** [comment]
@neclepsio 

As of today you can use `@click.native="myMethod"` 

but I did not document it. and probably better to dispatch @click like other components do. also I will probably document the way to catch click on start/end details as well. I plan to do it for next release once I have rebase on MDCWeb 0.30

What I want to invesitgate is the v-on="$listeners propagration, to allow finer interaction handler granularity. will probably do it in a second step as a generic design pattern for all components ...

**Comment by stasson** [comment]
didn't want to close ... just tired tonight ... sorry about that
