### ISSUE TITLE
mdc-drawer-item selected and activated

### ISSUE THREAD

**Issue by neclepsio** [stasson/vue-mdc-adapter#247]
Similar to #235, mdc-drawer-item should also provide selected and activated props.

**Comment by stasson** [comment]
ok

**Comment by stasson** [comment]
@neclepsio 

adding mdc-list-item--activated as default router_link active class. also 
adding activated prop to force it if u do not use router-link mode.

**Comment by neclepsio** [comment]
I'm not sure it works: I'm not using the router, and adding `:activated="true"` does not add any classes. Maybe there should be a comma instead of dot in line 4 of mdc-drawer-item.vue (currently `:class="[classes. itemClasses]"`)?

**Comment by neclepsio** [comment]
@stasson just to make sure you get notified of my previous comment (ther issue should be reopen if I'm not wrong).
