### ISSUE TITLE
mdc-textfield readonly attribute support 

### ISSUE THREAD

**Issue by euclides-jr** [stasson/vue-mdc-adapter#250]
Hi there,
Please add support for readonly attribute on mdc-textfield input. Thanks

**Comment by stasson** [comment]
@euclides-jr 

Can you give more details about what u expect ?

**Comment by euclides-jr** [comment]
Sure, I'm talking about the native readonly HTML input attribute, you could get it from props and pass to the input tag. I can submit a PR for you if you allow me.

**Comment by stasson** [comment]
Yes do not hesitate to PR
