### ISSUE TITLE
mdc-tab: property link is missing on custom-link

### ISSUE THREAD

**Issue by getriebesand** [stasson/vue-mdc-adapter#256]
and on route change the tabs doesnt update the active state.

I have build my tab content with swiper (https://github.com/surmon-china/vue-awesome-swiper)
Now I can slide with touch or mouse. Route will be updated on slideChange. But the right mdc-tab will not be active.

btw: thanks for making this and your realy fast response and bugfixing :)

**Comment by stasson** [comment]
@getriebesand 

should be closed with 0.10.0 now
