### ISSUE TITLE
Documentation standard

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#26]
Before we get too far into writing documentation, we should standardize the format. I think https://github.com/vue-styleguidist/vue-styleguidist might be the way to go.

**Comment by stasson** [comment]
@griest024 

Any reason you close this one? You think vue_styleguidist does not fit the bill?

**Comment by rafaesc** [comment]
Hi, I think that vue-styleguidist could help you keep documentation of your props automatically, and show a playground of your components.

Look at these examples:
http://rafaelescala.com/vue-styleguide/
https://croudsupport.github.io/Croud-Style-Guide/technical/
