### ISSUE TITLE
Modules not  found in TypeScript components

### ISSUE THREAD

**Issue by SirAuron** [stasson/vue-mdc-adapter#263]
Hi there.

I'm quite new to Vue and I'm trying to use your adapter into a TypeScript Vue component.
However, when I try to build the components with `npm run dev`, TypeScript compiler tells me that it can't find vue-mdc-adapter.

I've tried to remove all `lang="ts"` declarations inside my _.vue_ components, therefore changing from TypeScript to normal JS,  and renamed the main file from _app.ts_ to _app.js_. This time, by running `npm run dev` everything compiles correctly.

I've already did all the configurations for TypeScript (adding vue.d.ts, the WebPack configuration and tsconfig.json) and my online research provided meager results.

Do you have any idea if I'm missing something or if there is a way to properly import components into a _.ts_ script?

**Comment by stasson** [comment]
I have not tried typescript with vuejs yet. 

from the [doc](https://vuejs.org/v2/guide/typescript.html), looks like  typescript needs some declaration to recognize a component properly. Not sure how to support that...

**Comment by SirAuron** [comment]
Sorry for the long delay on this issue. In fact I've managed to solve it quite some time ago, but I wanted to be sure that everything was working before I closed this.

Anyway, onto the solution.

Even though I had correctly set up TypeScript and Vue configurations to make them work together, I was missing a simple fact.
Even if TS is just a superset of JavaScript and all JS code is valid TS code, by default TypeScript compiler does NOT accept `.js` files as input: you have to enable them first.

To achieve this, go to your main `tsconfig.json` file of your project. Inside `"compilerOptions"` voice, add the following specification:
```
[...],
"allowJs": true,
[...],
```
This will allow `.js` files to be compiled.
