### ISSUE TITLE
fix(slider): slider thumbContainer is offset when drawer open/close

### ISSUE THREAD

**Issue by stasson** [stasson/vue-mdc-adapter#268]
need either 
- [ ] a way to dispatch layout width changes to the slider to force foundation.lauot()
- [ ] find a working ResizeObserver polyfill for vue

**Comment by liederer** [comment]
I've been facing this issue for 30 minutes. Looked for an similar existing issue here. And there is one. Opened about an hour ago by you! 😄 

This project is great, especially thanks to the direct use of the MDC adapters, it offers almost a native feeling (in contrast to all the other material vuejs libraries out there). 

Thank you for your effort! 👍
