### ISSUE TITLE
Vue MDC Doesn't support Select values of non-string type

### ISSUE THREAD

**Issue by coogle** [stasson/vue-mdc-adapter#275]
I have an <mdc-select> component I am trying to use that I want to bind using non-string values, but it seems the mdc-select component only allows String values:

```
<mdc-select v-bind:model="currentLocation" label="Location">
       	<mdc-option v-for="location in locations" :key="location.id" v-bind:value="location">@{{ location.name }}</mdc-option>
</mdc-select>
```

**Comment by stasson** [comment]
@coogle 

yes, as of today, value must be a string because it may be stored in a real html value attribute `<option value="">`.  

I guess I could change that by with some value map, but that's complex. Need to think about it ...
In the mean time, could you set value to the key or index so the v-model would return the id and allow to retrieve the location?  would that work for you ?

**Comment by coogle** [comment]
Unfortunately I can't get a default value to work at all... I have as data:

```
		currentLocationId : {{ $locations[0]['id'] }},
		currentLocation : @json($locations[0]),
		locations : @json($locations),
```

(where 'id' is an integer)

The goal is to have the select default to the "current" location object, then update the `currentLocation` data value any time a new one is selected and I can't get it to work at all. `locations` is an array of location objects with an integer key `id`.

**Comment by stasson** [comment]
Can you send me a json dump of your `locations` object. I'll have a look ...

**Comment by coogle** [comment]
```
[{"id":1,"portal_id":"internal","name":"Office One","address_1":"22731 Kirsten Drives","address_2":"Suite 874","city":"West Jerrold","state":"KS","zipcode":"09672-5406","phone_number":"14353463554","fax_number":"3475021169","notes":"Voluptate nulla est nihil ea. Dolorem tempora et vitae dolorum voluptatem vel. A officia pariatur aut saepe consequatur.","created_at":"2017-12-13 08:12:16 UTC","updated_at":"2017-12-13 08:12:16 UTC","deleted_at":null,"pretty_phone_number":"+1 435-346-3554","pretty_fax_number":"+1 347-502-1169","hours":[{"day_of_week":"mon","opens_at":{"date":"2018-02-21 06:00:00.000000","timezone_type":3,"timezone":"UTC"},"closes_at":{"date":"2018-02-21 18:00:00.000000","timezone_type":3,"timezone":"UTC"}},{"day_of_week":"tue","opens_at":{"date":"2018-02-21 05:00:00.000000","timezone_type":3,"timezone":"UTC"},"closes_at":{"date":"2018-02-21 18:00:00.000000","timezone_type":3,"timezone":"UTC"}},{"day_of_week":"wed","opens_at":{"date":"2018-02-21 09:00:00.000000","timezone_type":3,"timezone":"UTC"},"closes_at":{"date":"2018-02-21 18:00:00.000000","timezone_type":3,"timezone":"UTC"}},{"day_of_week":"thu","opens_at":{"date":"2018-02-21 08:00:00.000000","timezone_type":3,"timezone":"UTC"},"closes_at":{"date":"2018-02-21 17:00:00.000000","timezone_type":3,"timezone":"UTC"}},{"day_of_week":"fri","opens_at":{"date":"2018-02-21 09:00:00.000000","timezone_type":3,"timezone":"UTC"},"closes_at":{"date":"2018-02-21 17:00:00.000000","timezone_type":3,"timezone":"UTC"}},{"day_of_week":"sat","opens_at":{"date":"2018-02-21 06:00:00.000000","timezone_type":3,"timezone":"UTC"},"closes_at":{"date":"2018-02-21 18:00:00.000000","timezone_type":3,"timezone":"UTC"}},{"day_of_week":"sun","opens_at":{"date":"2018-02-21 06:00:00.000000","timezone_type":3,"timezone":"UTC"},"closes_at":{"date":"2018-02-21 18:00:00.000000","timezone_type":3,"timezone":"UTC"}}]}]
```

**Comment by stasson** [comment]
for now, what about this: compute a location map using id as key

```html
<template>
  <mdc-select 
    :model="currentId" 
    label="Location">
    <mdc-option 
      v-for="location in locations" 
      :key="location.id" 
      :value="location.id"
    >@{{ location.name }}</mdc-option>
  </mdc-select>
</template>

<script>
export default {
  data() {
    return {
      locations: [],
      currentId: undefined
    };
  },
  computed: {
    locationMap() {
      return this.locationMap.reduce((map, location) => {
        return (map[location.id] = location);
      }, {});
    },
    curentValue() {
      return this.currentId ? this.locationMap[this.currentId] : {};
    }
  }
};
</script>
```
> didn't test it, but think it should work. perf should be ok provided the locations do not change too often and table is not too big.

> I thinking the only issue with removing the String constraints on value is if you render a native select (ios or android case), it does not play well with `<option>` attribute. but if you do not care about native rendering, I could remove the constraint... I'll see what i can do ...

**Comment by getriebesand** [comment]
I have the same problem at the moment.
id is a number but option value needs to be string.
is it possible to set
value: [String, Number] on mdc-options prop?

**Comment by stasson** [comment]
Found a Hack to get `[Number, String, Object]`
we'll release it soon ...

**Comment by stasson** [comment]
Unfortunately the hack is not working. it's buggy, had to revert :(

**Comment by coogle** [comment]
Bummer! I'm still in need of this for sure -- our entire project uses integer-based keys and having to mess around just trying to get something simple like this working is a major negative! For now I'm going to try to move on to another thing and hope you can find a fix to make this work for real soon!

**Comment by stasson** [comment]
> something simple like this 

not simple to find a valid implementation... I'll try to figure out something...

waiting for that you can always [wrap the select](https://codepen.io/stasson/pen/gvQWEQ)

**Comment by stasson** [comment]
I could use WeakMap to track the value but need a polyfill for IE11

**Comment by stasson** [comment]
outdated
