### ISSUE TITLE
mdc-dialog: prevent closing on accept

### ISSUE THREAD

**Issue by getriebesand** [stasson/vue-mdc-adapter#278]
I need to validate inputs and prevent closing if they are not valid.
There is an open issue on mdc https://github.com/material-components/material-components-web/issues/1323

is it possible to work around that while this issue is open? Maybe a footer slot so I can insert my own buttons and handle closing and accept by my self.

**Comment by getriebesand** [comment]
If I reopen the dialog immediately I have no flickering effect. So this is working for me and issue can be closed

**Comment by stasson** [comment]
@getriebesand 
understood, I guess I'll add the ability to implement your own behavior in a footer slot and expose the accept/cancel properties

**Comment by stasson** [comment]
@getriebesand 

so after playing with the dialog component, here is what I figured:

1. it's not straight forward to allow slot based footer customization. the internals of the MDCWeb Dialog assumes you always have an accept button, and pushing it into a secondary slot forces me to add a lot of logic which is not really "vue friendly", if I want to get focus, ripples, accept logic to work...

2. Another solution would be to expose the accept button disabled attribute as a dynamic property : so the accept button can be disabled until your validation logic enables it.  

I'll go for second solution for now. Hope this is ok with you

**Comment by getriebesand** [comment]
ok. But so the user can not click on the button, right? and I can not start the validation

**Comment by stasson** [comment]
yeah right. 

I was thinking your validation data would be reactive and you could aggregate the logic in a computed property which would then toggle the accept button disabled state. If your validation data are not reactive then yes we need a hack ...  I'm thinking ...

**Comment by stasson** [comment]
mmmh yeah I think I can hack it ...

**Comment by getriebesand** [comment]
client side validation can be reactive. But I have server side validation too.

ok..hack it :) but only if its not too complicated and maybe usefull to other. If not I can try to adapt the component by myself for my special usecase

**Comment by stasson** [comment]
Something like this

```html
<mdc-dialog ref="dialog" title="Dialog" accept="Accept" cancel="Decline"
  @validate="onValidate"
>Lorem ipsum dolor sit amet</mdc-dialog>
```

```javascript
export default {
  methods:{
    onValidate ({accept}) {
      let isValid = false
      // custom validation logic here
      // ..
      if (isValid) {
        accept()
      }
    }
  }
}
```

**Comment by pgbross** [comment]
Client side validation (at least) appears to work.
