### ISSUE TITLE
checkbox ripple effect not triggered on label

### ISSUE THREAD

**Issue by jerakode** [stasson/vue-mdc-adapter#28]
Hi.

1. Will ripple effeect will be added to radio?

2. Is that possible to make ripple effect toggle fully after click on label? In current version, If I click on label, not Checkbox by itself, the ripple is triggered, but it stay active. How to made it fully execute?

**Comment by stasson** [comment]
> Will ripple effeect will be added to radio?

Yes

> Is that possible to make ripple effect toggle fully after click on label? In current version, If I click on label, not Checkbox by itself, the ripple is triggered, but it stay active. How to made it fully execute?

I have a bug in the ripple I think I didn't put the ripple animations on the right element. I'll have a look...

**Comment by jerakode** [comment]
Thanks for feedback! I wrote an answer in previous issue. I understand that it's not a priority right now. Sorry for little spamming.

**Comment by stasson** [comment]
@jerakode 

FYI: while working on refactoring, I fixed checkbox, radio ripples and text field label bugs.

**Comment by jerakode** [comment]
@stasson cool! Nice to know dev in process. As for Nuxt and Docs site - have you tried it? FYI my offer to help is still valid, if ever needed.

**Comment by stasson** [comment]
@jerakode

Have not tried nuxt myself  yet. I have been buried with work lately. I guess I'll have more time next week. 

Regarding your offer to help, yes your help is very welcome. Are you OK to start working on a nuxt static version of the demo/docs site? You could start the nuxt project and when it begins to look good, it could replace my clumsy preview site? We can open another discussion to draft what needs to be done. 

Or did you have something else in mind?

**Comment by jerakode** [comment]
@stasson 

Got it, I have free time, so will be glad to be helpful. 

You have some particular thoughts how this demo site must be look like? 
I am thinking to make something between this two:
https://material.io/components/
https://material-components-web.appspot.com/

I could start a repo and when I make some progress I'll share the link. Is that ok?
