### ISSUE TITLE
TextField: attributes are moved from the outer-most element to inner input

### ISSUE THREAD

**Issue by alxpez** [stasson/vue-mdc-adapter#280]
Hi @stasson 

I've noticed that this has been included as a new feature in the latest version ([see commit](https://github.com/stasson/vue-mdc-adapter/commit/8cc88e267c3942a0441c123ae4ab9e554158102d)).

While this is definitely a great feature for most cases, I've encountered problems in an app I'm developing ([vuegg](https://github.com/vuegg/vuegg)). Basically in this app I check the outer-most element for things like 'id' and other vuegg-specific attrs to perform a series of actions... this new feature makes it crash.

I'm not sure if it's possible to keep certain attributes in the main/outer-most element (the 'mdc-textfield-wrapper' in this case), while keeping this feature untouched.

Do you have any idea on how to achieve this behaviour?

Thanks for your time, great work 👍

**Comment by alxpez** [comment]
I see that the [inheritAttrs:false](https://github.com/stasson/vue-mdc-adapter/blob/master/components/textfield/mdc-textfield.vue#L82) option is what's causing me the headache.

Does vue have any way around this for only specific cases? (I mean having **inheritAttrs:false** as the default behaviour, but with the possibility of passing certain attrs)

**Comment by alxpez** [comment]
@stasson, thanks man!

About hardcoding props into VMA code... I discarded that option from the beginning, since this is kinda personal problem on my side and a pretty specific one.
I thought about the wrapper, but unfortunately it won't work with my current implementation (also I would like to avoid it, since ultimately I want to generate the vue sources with plain VMA components... not polluting the code).

About the props needed, the really **ESSENTIAL** one is **id** (also is the only HTML native prop), other props are internal for my project (*egglement, componegg, containegg...*) and as such, they are probably irrelevant for the issue. However, let me know if there's something I can do.

Thanks for the quick response

**Comment by alxpez** [comment]
Oh man, [that](c8795d9)'s great!

I was actually looking at other alternatives, using the [data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) attributes to pass all my proprietary attrs as a form of data-*

But I have to say, that your solution saves me some good old refactoring work.

Thanks!

**Comment by stasson** [comment]
@alxpez 

v.0.11.1 has the select broken. you may want update to v0.11.2

**Comment by alxpez** [comment]
Perfect, I will do tonight 👍

**Comment by alxpez** [comment]
Hi @stasson and @pgbross,

I was updating [vuegg](https://github.com/vuegg/vuegg) to work with the latest version of vue-mdc-adapter (0.14.0) and I found that this issue has been reverted.

I looked through the commits that had happened since, it would be here https://github.com/stasson/vue-mdc-adapter/commit/d188482f0a85569c3e51955cae7226039d837af2.

Please let me know if this can be reverted back or if I need to look for a work around. Thanks!

**Comment by alxpez** [comment]
PS: can this issue be reopened? Or should I open a new one and reference this one?

**Comment by pgbross** [comment]
@alxpez 

I am sorry that you are having this issue again and thanks for bringing it to our attention.

Previously you have mentioned that it is the `id` attribute that you really need to be on the outermost rendered element (currently a `div` wrapper with class "mdc-textfield-wrapper").
For the actual implementation the relevant inner elements get an auto-assigned unique id so it would be reasonable for any user supplied `id` attribute to be on the outermost element. I suspect in most end-user use cases having the `mdc-textfield` element transparently wrap the scope attributes onto the inner `input` element is desireable so would be good to preserve, but `vue-mdc-adapter` can do this whilst also putting any user supplied `id` on the outer element.

Let me know if that is useful and if it would be sufficient to solve your issue.

**Comment by alxpez** [comment]
Hi @pgbross 

Thanks for the quick response.
I'm gonna do some small tests to see if having the **id** alone would suffice (that's my current believe, but I want to be certain).

I'll let you know as soon as I check all the outcomes, in the meanwhile I'm working with the v0.13.2.
