### ISSUE TITLE
Suggestion: point out material.io docs have more API calls

### ISSUE THREAD

**Issue by dmarcelino** [stasson/vue-mdc-adapter#295]
Hi @stasson,

Since this is my first issue let me start by saying I believe this project is the one that holds most potential in bringing Material design to Vue. The adapter approach is a good one and doesn't try to reinvent the wheel. Thanks for doing this!

I've just discovered the hard way (as in I had to look at the source code 🙂 ) how to programatically change tabs on `vue-mdc-adapter`. I think this should be on the docs somewhere and in fact it's already documented on the material.io docs at https://material.io/components/web/catalog/tabs/#the-full-foundation-api-1.
So my suggestion is that for each component doc page a paragraph mentioning the Foundation object and a link to the material.io docs is added (**EDIT**: the links to material.io docs are already there, only the introductory paragraph is needed, IMHO). That would help newcomers understand the full potential of the adapter.

**Comment by stasson** [comment]
@dmarcelino 

Ideally we should not need to do that as I should already have exposed and documented any foundation features in the adapter. Obviously I'way behind,  and your proposal is will help in the mean time ...
I'll try to add that for next release if I have a little bit of time.

**Comment by dmarcelino** [comment]
Documenting foundation features on the `vue-mdc-adapter` is even better, good stuff!

**Comment by stasson** [comment]
outdated
