### ISSUE TITLE
Drawer list item support for Nested Items

### ISSUE THREAD

**Issue by acorer** [stasson/vue-mdc-adapter#296]
I was going through the [Specification of Drawer list](https://material.io/components/web/catalog/drawers/) in MDC and quickly noticed that there was no way to get child items inside `<mdc-drawer-item>`.

It's important to have nested items in `<mdc-drawer-item>`, while I tried putting the nested list items inside a slot, but couldn't get the desired result.

Is there a way to have nested `mdc-drawer-item` that I am not aware about?

**Comment by stasson** [comment]
@acorer 

Hi, as far as I know MDCWeb doesn't support it yet. I'll have a look to check how tough it is to add it ...
