### ISSUE TITLE
Tabs: Uncaught TypeError: Cannot read property 'setActive' of undefined

### ISSUE THREAD

**Issue by dmarcelino** [stasson/vue-mdc-adapter#298]
Hi,

I'm using tabs bound to an array, something like this:

```javascript
    <mdc-tab-bar ref="tabBar" @change="onTabChange">
      <mdc-tab v-for="item in tabs" 
               :key="item.id" 
               :active="item.id === currentItem.id">{{ item.title }}</mdc-tab>
    </mdc-tab-bar>
```

And `tabs` is managed programatically. Whenever `tabs` shrinks, and the previous selected tab index is greater than the new array length, I get the following error:

```
Uncaught TypeError: Cannot read property 'setActive' of undefined
  at Object.setTabActiveAtIndex (mdc-tab-bar.vue:71)
  at eval (foundation.js:157)

requestAnimationFrame (async)
switchToTabAtIndex @foundation.js:155
resetTabs @mdc-tab-bar.vue:115
(anonymous) @mdc-tab-bar.vue:125
```

Looking at [foundation.js#L153-L158](https://github.com/material-components/material-components-web/blob/master/packages/mdc-tabs/tab-bar/foundation.js#L153-L158)

```javascript
    const prevActiveTabIndex = this.activeTabIndex_;
    this.activeTabIndex_ = index;
    requestAnimationFrame(() => {
      if (prevActiveTabIndex >= 0) {
        this.adapter_.setTabActiveAtIndex(prevActiveTabIndex, false);
      }
```

`foundation.js` seems to be attempting to activate the previous active Index. And then things break down at [mdc-tab-bar.vue#L69-L71](https://github.com/stasson/vue-mdc-adapter/blob/master/components/tabs/mdc-tab-bar.vue#L69-L71):

```javascript
      setTabActiveAtIndex: (index, isActive) => {
        this.tabs[index].setActive(isActive)
      },
```

I'll try to look deeper to see if I can find a solution.

**Comment by dmarcelino** [comment]
After taking a second look, I don't think we can do anything in `resetTabs()` to prevent this error, since we can't change `this.activeTabIndex_`, which the `foundation` class uses. The only thing that comes to mind is doing a check in `setTabActiveAtIndex()`, something like:

```javascript
      setTabActiveAtIndex: (index, isActive) => {
        if (index >= this.tabs.length && !isActive) {
          return; // previous active tab no longer exists, nothing to do
        }
        this.tabs[index].setActive(isActive)
      },
```

Not very elegant, but can't think of anything else. BTW, I've tested this on my project and it works.

**Comment by stasson** [comment]
@dmarcelino 

Thanks for the analysis.  I'll have a look to see if I can patch foundation for next release. feel free to send a PR if this is urgent for you...

**Comment by dmarcelino** [comment]
In terms of patching `foundation.js`, adding an upper bound check to line 156 does the trick:

```javascript
      if (prevActiveTabIndex >= 0 && prevActiveTabIndex < this.adapter_.getNumberOfTabs()) {
        this.adapter_.setTabActiveAtIndex(prevActiveTabIndex, false);
      }
```

But I'm not familiar with the codebase so not sure if that's the best approach.

The project where I'm using `vue-mdc-adapter` is still in its early stages, so no urgency for now.

**Comment by dmarcelino** [comment]
Awesome, thanks @pgbross!
