### ISSUE TITLE
Need prop 'class' for Accept and Decline buttons in mdc-dialog

### ISSUE THREAD

**Issue by acorer** [stasson/vue-mdc-adapter#309]
Given two buttons in the footer of `mdc-dialog` there needs to be a way by which we can give custom class to each of the buttons. 

Why? To custom class to a button that needs to be highlighted. For example A "Delete post?" dialog with two buttons 'Yes Delete' and 'Cancel', here 'Yes Delete' needs to have a red color to show that it is dangerous. 

Right now there is no way to add custom class for accept and decline buttons through `mdc-dialog` props.

**Comment by pgbross** [comment]
You should be able to put a class on the `mdc-dialog` element and then have CSS that targeted the buttons.
e.g.
```
<mdc-dialog ref="warning" title="Project not saved" @accept="onAccept" @cancel="onCancel" accept="Save"  cancel="Don’t save" class="my-dialog">
<!-- dialog contents -->
</mdc-dialog>
```
and CSS

```
.my-dialog .mdc-dialog__footer__button--cancel {
color: red;
}
```

but as of `vue-mdc-adapter` version 0.12.1 there is a bug that means the classes `mdc-dialog__footer__button--cancel` and `mdc-dialog__footer__button--accept` are not present.

I will raise an issue to get this added.
