### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by jerakode** [stasson/vue-mdc-adapter#31]
Hi there. It's me again. And sorry for delay. I see a bunch of changes since I gone :+1: 

Returning to Documentation site on Nuxt. I started repo - https://github.com/jerakode/mdc-vue-docs
Online demo - http://vue-mdc-adapter.surge.sh

If you have any suggestions, thoughts, please tell me.

Also, I dunno how better to organize communication, in this issue or other way - you decide.

**Comment by jerakode** [comment]
May be any example how would you like Documentation to be organized?

**Comment by stasson** [comment]
Wow! I like it a lot :)

Now I'm wondering if it's not too similar to Google's site. I guess we need to check their licensing. Also I'll think I'll contact mdc team to see if they agree we clone their web design. I do not see why they wouldn't agree but I want to be sure they're ok with that before we go to far ...

The way I imagine it: 
- Homepage would 
- Documentation Page would link to Guides Faq and HowTo pages
- Components page would  look a lot like MDC's one: same organisation with one page per component. but instead of having a separate page for the demo I would put examples of code and demo side by side

I guess we need to investigate generating the doc from package markdown. not sure how complex it would be...

That's exciting ...

**Comment by jerakode** [comment]
@stasson hi!

Yes, right now it's very similar, but I can easy make own styling. My purpose was to use main Material project style from start, then adjust it. We shouldn't use they icons (like I did in header), I think, but as for the rest - well, given the fact that it's a styleguides library, I think it's ok that everything looks similar :smile:  But no cloning like it is, in any case!

Anyway, will be happy to adjust it to Vue-flavor styling, it was in plans.

Agree as for the site structure, I have similar vision on my mind. I think we'll start from Homepage and Components, then will get to Documentation.

As for markdown, to use it with Nuxt we need to integrate it first. I saw few projects using it, and I'll investigate it (was looking for such solution for my own usecases anyway). But I believe there's not that much Docs, no? Is there anywhere I can look at it?

**Comment by jerakode** [comment]
Oh, sorry, I found https://github.com/stasson/vue-mdc-adapter/wiki/components

Well, this is great. I will look how to implement markdown parser into Nuxt.

**Comment by stasson** [comment]
for the markdown, the source which I keep up to date for each plugin is @ src/components/[plugin]/README.md

The one on https://github.com/stasson/vue-mdc-adapter/wiki/components may not be up to date with latest change. 

What I may do is to add component directory to npm release so we can find it versioned on unpkg.com I guess that would help...

**Comment by jerakode** [comment]
> What I may do is to add component directory to npm release so we can find it versioned on unpkg.com I guess that would help...

Yes this would be very convenient way to fetch the data.

**Comment by iamdubx** [comment]
@stasson hello. I made Nuxt integration with markdown, but can't make unpkg work. Cna you please help me? I got this `https://unpkg.com/vue-mdc-adapter@0.0.22/src/components/button/README.md`

It's my other work account

**Comment by iamdubx** [comment]
Ok, I installed it locally and now see why it doesn't exist. This files are not in npm. 
Are you planning to add them? I am ready to finish docs at last :smile:

**Comment by iamdubx** [comment]
I cloned the Wiki page into the project. Not sure if it's right way, but  I guess it's enough for development for now.

**Comment by stasson** [comment]
@iamdubx 

I added missing files, should be available now: (!! moved components from /src to / )

https://unpkg.com/vue-mdc-adapter@0.0.31/components/button/README.md

**Comment by iamdubx** [comment]
Cool, I will try and tell you how it goes.

**Comment by rafaesc** [comment]
Hi everyone, I think that vue-styleguidist could help you keep documentation of your props automatically, and show a playground of your components.

Look at these examples:
http://rafaelescala.com/vue-styleguide/
https://croudsupport.github.io/Croud-Style-Guide/technical/

You could also customize the page to be material

**Comment by stasson** [comment]
thanks @rafaesc for sharing this. vue-styleguidist looks really cool indeed.

For now I'm pretty busy at work and I just have the time to focus on fixing bugs and on setting up regression testing... 

I definitely would like to have an auto-generated style guide though and will investigate this further.
I'll come back to you...

**Comment by stasson** [comment]
for now and until 1.0 will stick to current doc.
