### ISSUE TITLE
Can't found dependency when using single component

### ISSUE THREAD

**Issue by jerakode** [stasson/vue-mdc-adapter#32]
When I try to use single component, for example button, not the whole library, I got an error that dependency not found.

```
This dependency was not found:

* vue-mdc-adapter/button in ./plugins/vue-mdc-adapter.js

To install it, you can run: npm install --save vue-mdc-adapter/button
```

Used the code from example 
```
import Vue from 'vue'
import VueMdcButton from 'vue-mdc-adapter/button'

Vue.use(VueMdcButton)
```
When import whole `vue-mdc-adapter` everything works, but if I want to use just a few components?

**Comment by stasson** [comment]
should be fixed with latest ^0.0.33. need to check...
