### ISSUE TITLE
Named exports are not supported in *.vue files.

### ISSUE THREAD

**Issue by Maxador** [stasson/vue-mdc-adapter#326]
https://github.com/stasson/vue-mdc-adapter/blob/66b27e843528d640006c04a539558368ca428da9/components/menu/mdc-menu.vue#L18

This line cause an error in the console. I guess it's only a mistake since the `Corner` was imported just before that and there's no need to export it.

**Comment by pgbross** [comment]
The export was added to have the component be able to export constants that you want defined to use with that component, namely the values for setting the corner alignment. It is supposed to be supported in current `vue-loader` but looking at comments in the `vue-loader` issue list I am not sure how robust or useful this is at the moment.

As this is undocumented in `vue-mdc-adapter@0.13.0` it should be removed at this time, and if it is needed in future we can find a better way of re-exporting the `Corner` constants.
