### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by ljcucc** [stasson/vue-mdc-adapter#332]
I got an exception when I using drawer: `Uncaught TypeError: Cannot read property 'style' of undefined`
I don't know what is going on and it still throw exception at any time.

Thanks!

**Comment by pgbross** [comment]
Thank you for filing your issue. `mdc-drawer` is working for me and does not give me any exception when running the [demo](https://stasson.github.io/vue-mdc-adapter/#/component/drawer) so we need some more information to try and reproduce the fault.

Please can you give more information about the exception and your setup/configuration. Try and include information on which vue-mdc-version, which browser and which OS you are using as well as the steps to reproduce the bug. If you have a [CodePen](codepen.io) that demonstrates the fault that would be useful, and/or try and include line number and module name from the exception.

thanks,
--philip

**Comment by pgbross** [comment]
Please reopen this issue if you have more information that may help reproduce the issue.
