### ISSUE TITLE
Tab component router integration - active link

### ISSUE THREAD

**Issue by albert0815** [stasson/vue-mdc-adapter#341]
Hi,

I am not really sure whether this is actually a bug or it works as expected. But in case it works as per the component expectation correct maybe you can help me to get around it anyway. The issue I am experiencing is about the selected tab (the selected tab which should be shown underlined).

I am using the mdc-tab-bar component and the "to" attribute to work with vue router. If I have a single page and navigate on that page the selected tab always is the correct one. But if I do a full reload of the page (or in other words: if I navigate to that page with a direct link) then always the first tab is the selected one. I would expect the one which is identified as active as per the router-to attribute to be the active one.

I created a sample for this: https://codepen.io/anon/pen/Brmabr - if you click on "Go to bar" you can see that there is a inconsistency between the active router and the selected tab.

I tried to fix this in my component with something like:

```
          this.$refs.tabs.tabs.forEach((t) => {
            if (t.$el.classList.contains("router-link-active")) {
              var index = this.$refs.tabs.tabs.indexOf(t);
              this.$refs.tabs.foundation.switchToTabAtIndex(index, true);
            }
          });

```
But this does not seem to work in all cases. If the component is reused due to a navigation I am not able to use that method, it works though for direct links.

Can you please let me know whether you think this is a bug in vue-mdc-adapter? Or whether you at least understand my problem?

Thank you for your help!

### What vue-mdc-adapter Version are you using?
0.10.0

### What browser(s) is this bug affecting?
Chrome 65.0.3325.181 (but I think it is not depending on browser)

### What OS are you using?
Windows 7

### What are the steps to reproduce the bug?

1. Open https://codepen.io/anon/pen/Brmabr
2. Click on "Go to Bar"
3. See that the active tab (underlined one) still is "Foo" while the active router link is "Bar" (green one)

### What is the expected behavior?
Active tab should be Bar (mdc-tab component should respect navigation).

**Comment by pgbross** [comment]
So I have a had a similar problem (I am not using the `router-link` or `to=` functionality in my application, but encounter the same kind of need to set the active tab according to the current route.

My slightly hacky solution was to add a watcher on the current route's name, and when it changes call a method to update the active tab (quite similar to your suggestion above, but by using the route name it is *after* the route navigation has completed).

I have put an example in [https://codepen.io/anon/pen/OvOMxB](https://codepen.io/anon/pen/OvOMxB).

Basically:

add
```
  watch: {
    '$route.name'(nv) {
      this.setTab();
    },
  },
  methods:{
    setTab(){
      const tabbar = this.$refs.tabbar;
      if (tabbar) {
        const index = tabbar.foundation.getActiveTabIndex();
        if (index !== _tabs[this.$route.name]) {
          tabbar.foundation.switchToTabAtIndex(_tabs[this.$route.name], false);
        }
      }
    }
  }
```

and modify the routes to have names and a simple map for name to index.

```
const _tabs = {
  foo: 0,
  bar: 1,
};
const routes = [
  { path: '/foo', name:'foo', component: Foo },
  { path: '/bar', name: 'bar', component: Bar }
]
```
This appears to give the behaviour you are after I think.

> Note: the tab-bar cannot have a selected index outside of the range of tabs so I am not sure if it is possible to have no tab selected.

Hope that helps.

**Comment by albert0815** [comment]
Hi pgbross,

thank you for the immediate response! Yea, that basically helped. I was able to adapt your suggestion to my project and it works fine in all situations I tested.

As you say this feels more like a hack or workaround than a good solution. Do you think it is possible / intended to support this within the tab component itself? For me it feels that the behaviour of the tab component is unexpected.

Thanks!

**Comment by pgbross** [comment]
@albert0815 
Glad that helped. 
The `material-components-web` goal is to provide good design for the web based on material design principles and, at least initially, `vue-mdc-adapter` is integrating that with `Vue` [Using Foundations and Adapters](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md#the-advanced-approach-using-foundations-and-adapters). 

To integrate further with third party libraries such as `vue-router`, `vuex` etc needs to be carefully considered. For example integrating with the specifics of how `vue-router` is implemented ties you to that library (I do not know if anyone actually ever uses a different router). If one did integrate such behaviour it may not be what every user of tab-bar wants so how do you override it - ie the library providing access to the Material Design UI is becoming bound with some higher level behaviour. Also as I mentioned in my comment, I happen not to use `router-link` or `to=` attributes but have the same requirement so how do you capture the behaviour without the library becoming too opinionated (ie. requiring using the `to=` to get some behaviour).

I am only commenting as one point of view to illustrate some of the things that need considering.
