### ISSUE TITLE
[Bug] Select component is not correctly rendered on mobile browsers

### ISSUE THREAD

**Issue by SirAuron** [stasson/vue-mdc-adapter#348]
### What vue-mdc-adapter Version are you using?
vue-mdc-adapter@0.9.2

### What browser(s) is this bug affecting?
 (Mobile versions)
Edge V. 1.0.0.1726
Chrome V. 65.0.03325.109

### What OS are you using?
Android 5.1.1 (and Chrome 65 for Windows 10 when testing from PC)

### What are the steps to reproduce the bug?

Create a select element,
then visualize it from a mobile browser.

For example it's sufficient to go to your example [here](https://stasson.github.io/vue-mdc-adapter/#/component/select) and from Chrome devtools triggering the mobile visualization.

### What is the expected behavior?

Browser default select dropdown arrow should be visible while the arrow added through background image should be hidden.

### What is the actual behavior?

On the select there are two visible arrows.

### Any other information you believe would be useful?
I think that the error is generated by `.mdc-select` class, which adds a `background-image: url(data:image...)` to the select tag.

Another interesting thing is that I tried the same on Firefox Quantum mobile, but the result was very different. Firefox simply displayed the component like the desktop version, therefore not using the mobile select default html element (which I presume is the correct way to render select on mobile since both chrome and Edge did the same).

**Comment by pgbross** [comment]
The underlying `material-components-web` implementation of the Select component removed the support for [CSS only](https://github.com/material-components/material-components-web/pull/2116) select v0.30.0 but the mdc-select vue component has not yet been updated to reflect that change (it should be).

Also `material-components-web` is changing the underlying implementation of Select to use the native element in a future release, so the behaviour on mobile should be more consistent when that happens.

**Comment by pgbross** [comment]
Resolved in v0.14.0
