### ISSUE TITLE
Need step prop on mdc-textfield to allow decimal values on input type number

### ISSUE THREAD

**Issue by acorer** [stasson/vue-mdc-adapter#352]
When using `mdc-textfield` along with `type="number"` prop, we can use whole number inputs like 100, 200, without any validation errors, However if we try to input numbers like 123.45, the `mdc-textfield` gives a validation error. 

I encourage to add `step` prop on `mdc-textfield` which will allow decimal input numbers on input `type='number'`.

The step property is explained [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input) at MDN

**Comment by pgbross** [comment]
In [commit](https://github.com/stasson/vue-mdc-adapter/commit/d188482f0a85569c3e51955cae7226039d837af2) (in `v0.13.5`) the native input element of `mdc-textfield` was transparently wrapped so attributes like `step` are automatically supported.

Until the next release of `vue-mdc-adapter`, however, the `type="number"` will give a validation error as it was not supported until fix #347.

**Comment by pgbross** [comment]
Resolved in v0.14.0
