### ISSUE TITLE
Remove mdc-card legacy layouts

### ISSUE THREAD

**Issue by pgbross** [stasson/vue-mdc-adapter#367]
### What vue-mdc-adapter Version are you using?

> 0.13.5

### What browser(s) is this bug affecting?

> Version 66.0.3359.66 (Official Build) beta (64-bit)

### What OS are you using?

> Fedora 28 4.16.0-300.fc28.x86_64

### What are the steps to reproduce the bug?

`mdc-card` legacy layouts are not supported by underlying `material-components-web`

Issue #258 tries to preserve legacy behaviour. Long term this seems like it will lead to extra support requirements as the `material-components-web` has not stabilised and `vue-mdc-adapter` will then be adapting and providing unique behaviour. If legacy behaviour/design is useful perhaps this could be put  into a separate library with its own goals, leaving `vue-mdc-adapter` to focus  keeping up with MDC updates.

As an alternative to a separate library, if that requires duplication of code for example, could legacy behaviour be implemented via a plugin system?

**Comment by stasson** [comment]
outdated
