### ISSUE TITLE
Styles are doubling up for some reason

### ISSUE THREAD

**Issue by kyoukhana** [stasson/vue-mdc-adapter#37]
When I include the library in my project like this.  The css is doubling up in the inspector for the library. I download your demo it isn't using vue-mdc-adapter it has all the sub imports for each component.  Is there a way we can resolve this or is it something I am doing wrong

```
/*Import declarations */
import Vue from 'vue'
import VueMDCAdapter from 'vue-mdc-adapter'
import VueRouter from 'vue-router';


Vue.use(VueMDCAdapter);

/*Routes*/
import siteRoutes from './routes/site'

/*Define Routes Object */
const loadRoutes = [
    ...siteRoutes
];

/*Define Router */
const router = new VueRouter({
    hashbang: false,
    linkActiveClass: 'active',
    mode: 'history',
    routes:loadRoutes
});

Vue.router=router;
App.router=router;
new Vue(App).$mount('#app');

```

**Comment by stasson** [comment]
Hello, 

I do not think you are doing anything wrong.
 
I'm not sure what you mean by the _inspector for the library_ can you give me more detail, I'd like to check which part of the CSS is duplicated. I may have some issue with my imports.  Also the way I am building vue-mdc-adapter for npm distribution doesn't split css and dosent have css optim which usually removes duplicates. But I would have expected the de-duplication to happen on your production build...

I need to look into this ...

**Comment by stasson** [comment]
may be related to https://github.com/webpack-contrib/sass-loader/issues/145

**Comment by stasson** [comment]
now using direct css import from mdc
still couple of duplicate in dev mode.
can't see no more duplicate for prod builds
