### ISSUE TITLE
mdc-switch always renders in form-field wrapper if has a label

### ISSUE THREAD

**Issue by pgbross** [stasson/vue-mdc-adapter#373]
### What vue-mdc-adapter Version are you using?

> 0.13.5

### What are the steps to reproduce the bug?

> 1. Use mdc-switch with label
> 2. Markup has a `mdc-form-field` wrapper

### What is the expected behavior?

> Should not wrap in mdc-form-field unless wanted.

### What is the actual behavior?

```
<div class="mdc-switch-wrapper mdc-form-field">
 <div class="mdc-switch">
   <input type="checkbox" id="_vma_75" class="mdc-switch__native-control"> 
   <div class="mdc-switch__background">
     <div class="mdc-switch__knob"></div>
   </div>
 </div> 
 <label for="_vma_75" class="mdc-switch-label">switch off</label>
</div>
```

### Any other information you believe would be useful?
Perhaps `vue-mdc-adapter` should provide an `mdc-form-field` component to allow an end user easy control aligned with underlying `material-components-web` library.

**Comment by stasson** [comment]
outdated
