### ISSUE TITLE
mdc-textfield: Pass id attribute from scope onto root element

### ISSUE THREAD

**Issue by pgbross** [stasson/vue-mdc-adapter#396]
### What vue-mdc-adapter Version are you using?

> 0.14.0

### What are the steps to reproduce the bug?

> 1. Use mdc-textfield with an id attribute
> 2. Markup does not include the id attribute on the root element

### What is the expected behavior?

> Should pass the id to the root elemennt.

### What is the actual behavior?

Scope attributes pass transparently to the underlying native element (eg. input).

### Any other information you believe would be useful?
Transparently wrapping the scope elements onto the inner native control gives the best general behaviour for most users/use cases, but as they have auto generated ids it should be safe to put any user supplied id on the root element. In one issue, #280, there is a possible use case.

**Comment by alxpez** [comment]
@pgbross 

I can confirm that having the **id** attribute on the root element will solve all my problems.
Regarding the other "_vuegg-specific_" attributes that I'm using, I've decided to refactor my code (and take the correct approach), passing these through as _data-*_ attrs.

BTW, I've noticed that also the **select** happen to have the same problem... I haven't look into it, but I would guess that the select component uses an input inside it?

Thanks for the support!
