### ISSUE TITLE
[Bug] Adapter components keep throwing warning after migrating from V0.13.5 to V0.14.0

### ISSUE THREAD

**Issue by SirAuron** [stasson/vue-mdc-adapter#400]
### What vue-mdc-adapter Version are you using?

0.14.0

### What browser(s) is this bug affecting?

Tested on:
Chrome 65.0.3325.181
Firefox Quantum (59)

### What OS are you using?

Windows 10

### Description

I've recently updated vue-mdc-adapter from 0.13.5 to 0.14.0
While using 0.13.5 version of the library, my code did not give any warning at all.
After the upgrade, each vue-mdc-adapter component keeps throwing at me a warn error like this one:

```
[Vue warn]: Property or method "vma_uid_" is not defined on the instance but referenced during render.
Make sure that this property is reactive, either in the data option, or for class-based components,
by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in --->
<MdcDialog> at node_modules/vue-mdc-adapter/components/dialog/mdc-dialog.vue
   <SettingsSocialAccount> at resources/assets/js/logged/pages/settings/components/SettingsSocialAccount.vue
	 <SettingsPage> at resources/assets/js/logged/pages/settings/SettingsPage.vue
	   <Router> at resources/assets/js/logged/pages/Router.vue
		 <Root>
```

My current setup is:
Vue (and vue-template-compiler): 2.5.16
vue-loader 13.7.1

To compile my assets I'm using laravel-mix 1.7.2 to wrap webpack, but with some custom specifications:
```
rules: [
	...,
	{
		test: /(@material|vue-mdc-adapter).*\.js$/,
		loader: "babel-loader",
		include: [
			path.resolve(__dirname, "node_modules/@material"),
			path.resolve(__dirname, "node_modules/vue-mdc-adapter"),
		],
		options: Config.babel(),
	},
	...,
]
```
where Config.babel() returns these options:
```
let defaultOptions = {
	cacheDirectory: true,
	presets: [
		['env', {
			'modules': false,
			'targets': {
				'browsers': ['> 2%'],
				uglify: true
			}
		}]
	],
	plugins: [
		'transform-object-rest-spread',
		['transform-runtime', {
			'polyfill': false,
			'helpers': false
		}]
	]
};
```
I do not know if this warning depends on my setup or not.

**Comment by stasson** [comment]
sounds like a regression, need to investigate ...
