### ISSUE TITLE
mdc-select: Pass id attribute from scope onto root element

### ISSUE THREAD

**Issue by pgbross** [stasson/vue-mdc-adapter#405]
### What vue-mdc-adapter Version are you using?

> 0.14.0

### What are the steps to reproduce the bug?

> 1. Use mdc-select with an id attribute
> 2. Markup does not include the id attribute on the root element

### What is the expected behavior?

> Should pass the id to the root elemennt.

### What is the actual behavior?

Scope attributes pass transparently to the underlying native element (eg. input).

### Any other information you believe would be useful?
Transparently wrapping the scope elements onto the inner native control gives the best general behaviour for most users/use cases, but as they have auto generated ids it should be safe to put any user supplied id on the root element.

**Comment by stasson** [comment]
@pgbross 

why do we need that ?

**Comment by pgbross** [comment]
Requested by @alxpez in #396

**Comment by stasson** [comment]
merged in #420
