### ISSUE TITLE
vue-mdc-adapter does not faithfully follow mdc web look and feel

### ISSUE THREAD

**Issue by jimbojetlag** [stasson/vue-mdc-adapter#411]
For example, compare [vue-mdc-adapter checkbox](https://stasson.github.io/vue-mdc-adapter/#/component/checkbox):
 
![image](https://user-images.githubusercontent.com/11205806/39207140-1fd4412e-47f7-11e8-9e5e-bdbe3194a4ae.png)

with the [original mdc checkbox](https://material-components-web.appspot.com/checkbox.html):

![image](https://user-images.githubusercontent.com/11205806/39207211-4ef740b4-47f7-11e8-9c21-08897a482332.png)

where the thickness of the check symbol is changed.

The whole point of using mdc is the way it adheres to MD specs. The adapters are not supposed to modify the styles.

**Comment by stasson** [comment]
@jimbojetlag 
thank you for letting us know, we'll investigate why we have this issue.

**Comment by pgbross** [comment]
It looks like the class on the path element of the svg element is missing the 'mdc' prefix. Specifically

```html
<path class="checkbox__checkmark-path"
                fill="none"
                stroke="white"
d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
```
should be

```html
<path class="mdc-checkbox__checkmark-path"
                fill="none"
                stroke="white"
d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
```
