### ISSUE TITLE
[Bug] mdc-select styles cannot be imported from vue-mdc-adapter/dist/select/styles

### ISSUE THREAD

**Issue by SirAuron** [stasson/vue-mdc-adapter#423]
### What vue-mdc-adapter Version are you using?

v0.15.0

### What are the steps to reproduce the bug?

1. In any of your project's `.scss`  files add `@import "~vue-mdc-adapter/dist/select/styles";`
2. Compile your assets

### What is the expected behavior?

Compilation should be successful and mdc-select style should be correctly imported.

### What is the actual behavior?

Compilation fails since there is no `./scss/mdc-select` inside `vue-mdc-adapter/dist/select` folder.

### Any other information you believe would be useful?

Just wanted to bring this to your attention even though I saw that this is a temporary fix (as stated in the very `vue-mdc-adapter/dist/select/styles` file), since in the [get started](https://stasson.github.io/vue-mdc-adapter/#/docs/getting-started) documentation it shows that is possible to import _a la carte_ plugins styles both from `dist` and `components` folders.

Using `@import "~vue-mdc-adapter/dist/select/styles";` instead of `@import "~vue-mdc-adapter/components/select/styles";` gives an error because in `vue-mdc-adapter/dist/select` folder there is no `scss` folder, which is present and works correctly in `vue-mdc-adapter/components/select/components` folder.

**Comment by MatthiasF999** [comment]
This bug also prevents importing the complete style `@import 'vue-mdc-adapter/dist/styles';`.

**Comment by stasson** [comment]
@SirAuron @MatthiasF999 

sorry about this issue, I was trying to fix a postcss issue while building MDCWeb 0.35 styles. unfortunately, I broke scss imports.

I also fixed scss distribution path hierarchy.  See [Getting Started](https://github.com/stasson/vue-mdc-adapter/blob/master/docs/getting-started.md#full-build)  and and new dist layout for [v0.15.3](https://unpkg.com/vue-mdc-adapter@0.15.3/dist/)

> BREAKING CHANGE: components directory is not part of the distribution anymore

> BREAKING CHANGE: styles are not located in 'vue-mdc-adapter/dist/components/...'
anymore. import them from 'vue-mdc-adapter/dist/...'

let me know if I can close this issue...

**Comment by MatthiasF999** [comment]
`@import 'vue-mdc-adapter/dist/styles';` now works.

**Comment by SirAuron** [comment]
Updated the project and tested it.
I can confirm that everything  works fine.
For me you can close this issue.
