### ISSUE TITLE
Use mdc-top-app-bar in layout-app

### ISSUE THREAD

**Issue by MatthiasF999** [stasson/vue-mdc-adapter#425]
### What vue-mdc-adapter Version are you using?

0.15.3

### What is the expected behavior?

The `layout-app` component should use `mdc-top-app-bar`.

### What is the actual behavior?

The `layout-app` component uses `mdc-toolbar`.

### Any other information you believe would be useful?

The existing `MDCToolbar` component and styles will be removed in a future release. Some of its functionality will be available in the `mdc-top-app-bar` package instead. Bugs and feature requests will no longer be accepted for the `mdc-toolbar` package. It is recommended that you migrate to the `mdc-top-app-bar` package to continue to receive new features and updates.

**Comment by DawidCyron** [comment]
This need a quick fix. I can't use `top-app-bar` because of that. It's half transparent, always moves along with user, and overall layout is broken beacuse of that.
