### ISSUE TITLE
refactor(top-app-bar): top app bar's navigation icon should be a button, not an anchor

### ISSUE THREAD

**Issue by rustemgareev** [stasson/vue-mdc-adapter#430]
`<a>`nchors lead users to some url, `<button>`s indicate a user's action.
Currently nav icon in the top app bar is an anchor. But in the most cases it's used for opening / closing the drawer (action). Even if nav icon is a "back" button, it can be made with `history.back()` method, not with storing a url. And, unlike an anchor, button doesn't add unnecessary hash to the url (which can be a problem in SPAs routing).

**Comment by dlucian** [comment]
Also, seems that since it changes the hash, it also interferes with vue-router, breaking the app. I tried `.native`, `.prevent`, anything that would prevent this behaviour but couldn't.
