### ISSUE TITLE
UID is only unique within components e.g. mdc-radio/mdc-checkbox

### ISSUE THREAD

**Issue by Lampy09** [stasson/vue-mdc-adapter#440]
### What vue-mdc-adapter Version are you using?

> 0.15.3

### What browser(s) is this bug affecting?

> All, however tested in Chrome 66.0.3359.181 

### What OS are you using?

> Windows 7

### What are the steps to reproduce the bug?
> Create a page with mixed components like mdc-radio and mdc-checkbox

### What is the expected behavior?

> When you click the label of a checkbox it shouldn't select the radio

### What is the actual behavior?

> See: https://jsfiddle.net/un2zuvLp/1/
> When you click the radio's and checkboxes everything goes fine. However when you select the label of a checkbox it will select a radio button. After inspecting the DOM I've noticed the ID's aren't unique (and those are based on the `UID`)

### Any other information you believe would be useful?
> I was only able to reproduce this in a webpack environment which uses the `index.js` file in the `dist` folder. When using `https://unpkg.com/vue-mdc-adapter` like I here: https://jsfiddle.net/g87px1tx/1/ everything works like a charm.
> It looks like the `UID` isn't shared among components.

> My initial project was created with Vue CLI with the `webpack` template
> Followed these instructions: https://stasson.github.io/vue-mdc-adapter/#/docs/getting-started (Webpack)

```
import VueMDCAdapter from 'vue-mdc-adapter'
Vue.use(VueMDCAdapter)
```

**Comment by stasson** [comment]
should be ok with next release
