### ISSUE TITLE
Dialog Does Not Open if Initial Open State is True

### ISSUE THREAD

**Issue by aeolingamenfel** [stasson/vue-mdc-adapter#446]
### What vue-mdc-adapter Version are you using?

>0.15.3

### What browser(s) is this bug affecting?

> Chrome 66.0.3359.181 (Official Build) (64-bit)

> UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

### What OS are you using?

> macOS 10.13.4

### What are the steps to reproduce the bug?

1. Create an instance of a `mdc-dialog` and set its initial bound value to `true`:
```HTML
<mdc-dialog v-model="isOpen"><!-- ... --></mdc-dialog>
```
```javascript
data() {
    return {
        isOpen: true
    };
}
```
2. Load the page with that dialog

### What is the expected behavior?

The dialog should open as soon as the page loads.

### What is the actual behavior?

The dialog does not fully open&mdash;the overlay is present (so elements on the page are non-interactive due to the opaque overlay), but the dialog is still hidden. 

### Any other information you believe would be useful?

My specific use case is I'm using Vuex for state, and I want this dialog to automatically open if the boolean state controlling the "is logged in" state for the app user is false. 

I've managed to find a workaround wherein I set the `isOpen` data to false, then manually toggle it to true using a `setTimeout` of 100ms, but this is obvious not ideal.

**Comment by stasson** [comment]
@aeolingamenfel 

Thxs for reporting this. the vmodel is indeed not initialized properly. I'll try to fix this asap
