### ISSUE TITLE
Icon Toggle disabled not working

### ISSUE THREAD

**Issue by perqin** [stasson/vue-mdc-adapter#447]
### What vue-mdc-adapter Version are you using?

> ^0.14.0

### What browser(s) is this bug affecting?

> Chromium Version 66.0.3359.181 (Official Build) Arch Linux (64-bit)

### What OS are you using?

> Linux archlinux 4.16.10-1-ARCH #1 SMP PREEMPT Mon May 21 07:57:23 UTC 2018 x86_64 GNU/Linux

### What are the steps to reproduce the bug?

> See Codepen: [https://codepen.io/perqin/pen/yENOrq](https://codepen.io/perqin/pen/yENOrq)

### What is the expected behavior?

> The toggle is disabled and the icon should not change when clicked.

### What is the actual behavior?

> The icon still changes between `toggle-on` and `toggle-off` though the toggle button is gray.

**Comment by stasson** [comment]
@perqin 

Looks like an MDCWeb issue. not sure it'll be fixed as IconToggle will be deprecated and replace with a new Icon Button component soon. 

will investigate if it is worth doing a quick workarrround or if better to go to new  IconButton ...
