### ISSUE TITLE
add support for type checking (typescript or flow)

### ISSUE THREAD

**Issue by veonua** [stasson/vue-mdc-adapter#451]
right now it is not possible to discover methods and types without digging in sources, 

it would be nice to have IDE hints, autocomplete, and flow check

**Comment by stasson** [comment]
@veonua 

I'm thinking of adding typescript support. 
not sure about how I can add support for flow.

**Comment by veonua** [comment]
TS would be great, thank you

vue supports flow in https://github.com/vuejs/vue/tree/dev/flow

**Comment by stasson** [comment]
@next #506
