### ISSUE TITLE
Dropdown menu is not possible in <mdc-drawer-list> with <mdc-menu-anchor>

### ISSUE THREAD

**Issue by veonua** [stasson/vue-mdc-adapter#455]
I am trying to reproduce dropdown menu as pictured 
https://material.io/design/assets/0B54x0KDcs5U-NC1tYmRKQWIzdDA/behavior-icon.png

### What vue-mdc-adapter Version are you using?

0.15.3

### What OS are you using?

all

### What is the expected behavior?

dropdown menu as 
https://material.io/design/assets/0B54x0KDcs5U-NC1tYmRKQWIzdDA/behavior-icon.png

### What is the actual behavior?

mdc-menu-anchor is not usable with lists, it either repeats for every item or anchored to bottom of the list 

my code is:

```
<mdc-drawer-list>
<mdc-drawer-item  v-for="(item) in workspaces"
                        :to="'/w/'+item.id"
                        :key="item.id">

        {{ item.name }}
        <mdc-menu-anchor class="mdc-list-item__meta">
          <i class="material-icons mdc-list-item__meta" v-on:click.prevent.stop="open=true"> more_vert</i>

          <mdc-menu v-model="open">
            <mdc-menu-item>A Menu Item</mdc-menu-item>
            <mdc-menu-item>Another Menu Item</mdc-menu-item>
           </mdc-menu>
        </mdc-menu-anchor>
      </mdc-drawer-item>
</mdc-drawer-list>
```

**Comment by stasson** [comment]
need to implement MDCWeb's new anchor strategy
will be done in @next #506
