### ISSUE TITLE
Textfields: outlined and boxed do not work when set to full width

### ISSUE THREAD

**Issue by bruno-fernandes** [stasson/vue-mdc-adapter#456]
Is there a reason for the **outlined** and **boxed** variations of the text fields not to work? I checked the code and it seems to be on purpose although can't find anything in the material specs that mention it. https://material.io/design/components/text-fields.html#outlined-text-field

Codepen preview: https://codepen.io/bruno-fernandes/pen/MXbQWP

**Comment by rustemgareev** [comment]
The reason is that VMA wraps text-fields with additional div `mdc-textfield-wrapper`, which isn't set to the full width by default. You should set its width to 100% to get the desired result:
```css
,mdc-textfield-wrapper {
  width: 100%;
}
```

**Comment by MatthiasF999** [comment]
I believe this is on purpose, since the [material.io web component docs](https://material.io/develop/web/components/input-controls/text-field/) state:

> NOTE: Do not use mdc-text-field--box or mdc-text-field--outlined to style a full width text field.

**Comment by bruno-fernandes** [comment]
@MatthiasF999 thanks for clearing that up!
