### ISSUE TITLE
Top App Bar incorrect styling

### ISSUE THREAD

**Issue by rrgahan** [stasson/vue-mdc-adapter#459]
### What vue-mdc-adapter Version are you using?

0.15.3

### What browser(s) is this bug affecting?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

### What OS are you using?

macOS High Sierra 10.13.5 (17F77)

### What are the steps to reproduce the bug?

Create a `<mdc-top-app-bar>` like the one included in the documentation.

### What is the expected behavior?

The documentation says by default, `short=false`, so I expected the element to be the width of the screen. I also expected the element to exist in `div.mdc-layout-app--toolbar-wrapper`.

### What is the actual behavior?

`short` defaulted to true. The element does not exist in `div.mdc-layout-app--toolbar-wrapper`, but as a `<header>` in `div.mdc-layout-app--content-wrapper`. I had to apply `margin-top: 56px` to `div.mdc-layout-app--content-wrapper` to have it not cover up the page title. The url changes when I close the nav drawer.

**Comment by rrgahan** [comment]
As I keep playing around with this I keep finding small bugs with it... In the deprecation notice for `<mdc-toolbar>` it was recommended to switch to `<mdc-top-app-bar>`, but it doesn't seem ready to replace all the functionality in the toolbar. What is your timeline for depreciation and having top app bar as a valid substitute?

**Comment by stasson** [comment]
@rrgahan 

not really my choice here: [MDCWeb ](https://material.io/develop/web/)  Team decided the deprecation. so today mdc-toolbar styles are not maintained any more. mdc-top-app-bar is not finished yet. I'm basically waiting for them to finalize it before really deprecating ...

anyway I'll have a closer look to the code to see if I'm not doing anything wrong with the mdc wrappers...

**Comment by rrgahan** [comment]
Totally understand! Thanks for giving the deprecation notice and working on finalizing. I'm assuming the docs will be updated when everything is finished up?
