### ISSUE TITLE
Snackbar not disappearing

### ISSUE THREAD

**Issue by rrgahan** [stasson/vue-mdc-adapter#460]
### What vue-mdc-adapter Version are you using?

0.15.3

### What browser(s) is this bug affecting?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

### What OS are you using?

macOS High Sierra 10.13.5 (17F77)

### What are the steps to reproduce the bug?

Create a snackbar without an action (or go to your docs, show the snackbar, and don't click the action).

### What is the expected behavior?

Snackbar should disappear. Without a timeout property, it should disappear in 2750 milliseconds. With the property, it should disappear in defined time.

### What is the actual behavior?

The snackbar does not disappear. On my own without the action, it never disappears, and with yours on the documentation, it only disappears on action click.

**Comment by progamax** [comment]
I have the same bug

**Comment by rchan** [comment]
I have the same too

**Comment by thehendrix** [comment]
Was this ever fixed?
