### ISSUE TITLE
Tricky alignment of slots within mdc-layout-app

### ISSUE THREAD

**Issue by andriytyurnikov** [stasson/vue-mdc-adapter#469]
### What is the expected behavior?
Main slot and drawer adjusted for toolbar by default

### What is the actual behavior?
Main slot and drawer are NOT adjusted for toolbar by default

### Any other information you believe would be useful?
I wonder if `.mdc-toolbar-fixed-adjust ` of the main slot, and `<mdc-drawer toolbar-spacer>` should become defaults

**Comment by K900** [comment]
`.mdc-toolbar-fixed-adjust` is also problematic with tabs - it still adds 64px of padding when 128px is needed. Sounds like it needs to be conditional.

```html
<main :style="{ paddingTop: $slots.tabs ? '128px' : '64px' }">
     <slot name="content" />
</main>
```

Is how I've worked around it on my end for now.

**Comment by stasson** [comment]
@next #506
