### ISSUE TITLE
Select component doesn't change value

### ISSUE THREAD

**Issue by coogle** [stasson/vue-mdc-adapter#476]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

vue-mdc-adapter is still under active development. You can see our current progress on [master](https://github.com/stasson/vue-mdc-adapter/tree/master).

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What vue-mdc-adapter Version are you using?

v0.5.3 (2017-11-29)

### What browser(s) is this bug affecting?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

### What OS are you using?

Mac OSX 10.12

### What are the steps to reproduce the bug?

I am using the <mdc-select> component as follows:

```
<mdc-select class="state-select" v-model="currentLocation.state" label="State">
 <mdc-option :key="abbr" v-for="(name, abbr) in us_states" :value="abbr">@{{ name }}</mdc-option>
 </mdc-select>
```
Where `currentLocation` is a `data` property

I am trying to "erase" my form by setting all the properties in `currentLocation` to an empty string (mostly) as follows:

```
			this.currentLocation = {
				"id": '',
				"portal_id" : "@portal(id)",
				"name" : "Unnamed Location",
				"address_1" : "",
				"address_2" : "",
				"city" : "",
				"state" : "",
				"zipcode" : "",
				"phone_number" : "",
				"fax_number" : "",
				"notes" : ""
			};
```

This works for everything except the `mdc-select` component. The `currentLocation.state` property is set to `''` but the visual still says the last selected value (i.e. 'Michigan'). You have to click a different state to re-sync the component.

### What is the expected behavior?

When I update the underlying data, the visual changes to match.

### What is the actual behavior?

It doesn't do that.

**Comment by MatthiasF999** [comment]
I cannot recreate this issue.
The only error I can see is that it should be `option `instead of `mdc-option`.

I created a fiddle at https://jsfiddle.net/MatthiasF999/eywraw8t/125188/ using your code.

Could you please create an example containing the bug to identify the problem.

**Comment by stasson** [comment]
@coogle 

are you really using v0.5.3 (2017-11-29)
can you reproduce on a more recent version ?

thxs
