### ISSUE TITLE
Animation bug caused from inputs having same ID

### ISSUE THREAD

**Issue by rrgahan** [stasson/vue-mdc-adapter#479]
### What vue-mdc-adapter Version are you using?

"vue-mdc-adapter": "0.15.3"

### What browser(s) is this bug affecting?

Chrome, Safari, and Firefox are all affected.

### What OS are you using?

MacOS High Sierra 10.13.5

### What are the steps to reproduce the bug?

Create a page with a `mdc-textfield` and `mdc-checkbox` on it. Visit the page and select the checkbox by clicking its label.

### What is the expected behavior?

I would expect that the animations for the textfield and checkbox would be independent of each other, but because the inputs share the same ID (and the labels share the same `for`), selecting the checkbox label triggers animation on the textfield.

**Comment by stasson** [comment]
@rrgahan 

if think this is a dup of #440 which has been fixed in v0.16.xx
would you mind checking ?

**Comment by stasson** [comment]
i'm closing the issue will reopen if you still have issues
