### ISSUE TITLE
Menu styles should import list styles

### ISSUE THREAD

**Issue by phillipCouto** [stasson/vue-mdc-adapter#482]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What vue-mdc-adapter Version are you using?

0.16.2

### What browser(s) is this bug affecting?

All

### What OS are you using?

macOS 10.13.5

### What are the steps to reproduce the bug?

1. Import only menu and button components and styles
2. Follow the example on the demo page
3. Click the button to open the menu
4. Notice how the list elements do not appear as in the demo

### What is the expected behavior?

The menu should render identical to the demo example of the menu component.

### What is the actual behavior?

The style does not match at all. It appears as if there is missing or overridden styles.

### Any other information you believe would be useful?

I was able to fix the issue by importing the styles for the list component. It would be ideal if the documentation was updated to reflect this requirement or the menu styles import the list styles as it seems it is a hard dependency and not optional.

**Comment by stasson** [comment]
@phillipCouto 

ty for reporting this. will have force menu to import list styles
