### ISSUE TITLE
closeDrawer must be renamed as close in mdc-drawer-item

### ISSUE THREAD

**Issue by crackmanix** [stasson/vue-mdc-adapter#484]
"closeDrawer()" must be renamed as "close()" in mdc-drawer-item.vue at line 54

When you click on an item of a temporary drawer you obtain this error : 

`Uncaught TypeError: t.mdcDrawer.closeDrawer is not a function
at click (VM195881 vue-mdc-adapter.min.js:59)
at i (VM195880 vue.min.js:6)
at HTMLAnchorElement.Rr.t._withTask.o._withTask (VM195880 vue.min.js:6)`

Linked to the pull request #477

**Comment by stasson** [comment]
#477 merged
