### ISSUE TITLE
@keypress.enter doesn't work?

### ISSUE THREAD

**Issue by coogle** [stasson/vue-mdc-adapter#486]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

vue-mdc-adapter is still under active development. You can see our current progress on [master](https://github.com/stasson/vue-mdc-adapter/tree/master).

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What vue-mdc-adapter Version are you using?

Latest from NPM install (just upgraded)

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

Mac OS X

### What are the steps to reproduce the bug?

This might be something I'm doing wrong but I can't get a @keypress.enter event to fire at all. I have something like this:

```
<mdc-list>
    <mdc-list-item>
       <mdc-textfield @keypress.enter="foo"></mdc-textfield>
    </mdc-list-item>
</mdc-list>
```

I can't get foo() to be called at all. Note this doesn't seem to be an issue with `mdc-list` either because I am also having the same problem with my login form. 

Is there something I am missing as to why @keypress.enter won't work?!

**Comment by stasson** [comment]
@coogle 

listeners on the component are being forwarded to the input element. 
so @keypress should work. seems to be working for me on master !?!

which vue version are u using ?
