### ISSUE TITLE
Tabs are not colored correctly by default.

### ISSUE THREAD

**Issue by K900** [stasson/vue-mdc-adapter#489]
### What vue-mdc-adapter Version are you using?

> 0.17.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> All OS

### What are the steps to reproduce the bug?

https://codepen.io/k900/pen/GBZeJr

### What is the expected behavior?

> Tabs should follow the toolbar text color (in this case, white)

### What is the actual behavior?

> Tabs are black

**Comment by stasson** [comment]
right MDCWeb Tabs can not know they are in a toolbar, and which is the text color of the toobar...
I need to investigate how I can do this.

in the mean  time, you can use MDCWeb sass mixins to color them
https://material.io/develop/web/components/tabs/tab/#sass-mixins
https://material.io/develop/web/docs/theming/#custom-themes

**Comment by K900** [comment]
Yeah, that's what I ended up doing. A separate style for tabs inside a toolbar should be possible as part of the toolbar component, but that seems hacky :(
