### ISSUE TITLE
Class constructor MDCRippleFoundation cannot be invoked without 'new'

### ISSUE THREAD

**Issue by rsjavier14** [stasson/vue-mdc-adapter#499]
Hello,
I have this problem with vuejs and laravel.

Specifically in the ripple class:
`export class RippleBase extends MDCRippleFoundation {
  static get MATCHES() {
.......}}`
When I navigate to a page, and execute this code :
`export const RippleMixin = {
  mounted() {
    this.ripple = new RippleBase(this)
    this.ripple.init()
  }
}`

My console show the folllowing output :

![captura de pantalla de 2018-08-07 13-14-44](https://user-images.githubusercontent.com/3706989/43791615-35891d10-9a44-11e8-857d-e7319fc7f166.png)

Is there any way to solve this?

**Comment by stasson** [comment]
@rsjavier14 

which version of vue-mdc-adapter ? 
can you share your package.json dependencies ?

**Comment by rsjavier14** [comment]
Hey @stasson ,
thanks for answering. I am using version 0.17.0, I leave the dependencies:

```
 "devDependencies": {
    "autoprefixer": "^9.1.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-3": "^6.24.1",
    "css-loader": "^1.0.0",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^1.1.11",
    "mini-css-extract-plugin": "^0.4.1",
    "node-sass": "^4.9.2",
    "postcss-loader": "^2.1.6",
    "resolve-url-loader": "^2.3.0",
    "sass-loader": "^7.1.0",
    "vue-loader": "^15.3.0",
    "vue-style-loader": "^4.1.1",
    "vue-template-compiler": "^2.5.17",
    "webpack": "^4.16.5",
    "webpack-cli": "^3.1.0"
  },
  "scripts": {
    "dev": "webpack --watch --mode=development"
  },
  "dependencies": {
    "classnames": "^2.2.6",
    "font-awesome": "4.7.0",
    "material-components-web": "^0.38.0",
    "material-icons": "^0.2.3",
    "vue": "^2.5.17",
    "vue-mdc-adapter": "^0.18.1"
  }
```

**Comment by rsjavier14** [comment]
Delete all the dependencies, reinstalled them and reconfigured everything and it works. I could not explain what the problem was. The issue can be closed. Thank you
