### ISSUE TITLE
@next

### ISSUE THREAD

**Issue by stasson** [stasson/vue-mdc-adapter#506]
# `@next`

MDCWeb foundation/adapter and theme strategy has changed a lot since the beginning of the project.
Same for Webpack/Rollup/Vue tooling. `vue-mdc-adapter` needs to be refactored in order to be able keep up. 

This issue is open to track/discuss the main changes for the next version.

## build env
- [x] resolve sass dependencies issues
- [x] cleanup obsolete dev dependencies
- [ ] migrate build chain to vue-cli 3 / typescript ?
- [ ] lerna multi-packages ?

## CI
- [ ] migrate CI to circleci 
- [x] migrate CI to gitlab
- [x] commitlint fails the mergerequest

## doc
- [x] vuepress crawlable doc
- [x] embeded playgound

## refactor
- [x] new adapter/foundation integration pattern ( class/styles/listener ...)
- [x] split pure MDCWeb features vs Helpers in separate packages
- [x] new test strategy
- [ ] e2e screenshot testing  ?

## new features
- [x] typescript support
- [x] align api on MDCWeb react and drop obsolete MDCWeb feature support
- [x] theming core & guide 
- [x] move vma extra features to an vma-extra package

**Comment by andriytyurnikov** [comment]
Maby using https://github.com/viljamis/vue-design-system is an attractive option?

**Comment by stasson** [comment]
@andriytyurnikov 

I really like what @viljamis is doing with vue-design-system. 
but MDCWeb already has a design system in place and I'm not sure I could get both working together ...

**Comment by andriytyurnikov** [comment]
@stasson it is sure a trade-off between **maintenance** of own solution and choices and having a **dependency**

As a first-time contributor, I would like to add that demo thing is working 
and it is quite lightweight, but to figure out that one has to change:
`demo/component.vue` and `demo/links.js`
to get the demo working, was a bit of a puzzle (sure not every day one gets new component added, but anyway).
Also, it looks like there is a shortage of sidebar icons for components 😉

**Comment by atishpatel** [comment]
Is there a place we can access the @next branch?

**Comment by luisquicidev** [comment]
> Is there a place we can access the @next branch?

+ 1
