### ISSUE TITLE
mdc-textfield: tabindex leading/trailing icons 

### ISSUE THREAD

**Issue by Lampy09** [stasson/vue-mdc-adapter#508]
### What vue-mdc-adapter Version are you using?

> 0.17.0

### What browser(s) is this bug affecting?

> All

### What OS are you using?

> All

### What are the steps to reproduce the bug?

> use multiple `mdc-textfield`s in with a leading icon
> use tab to navigate to the next field
> the leading icon is focused while you expect the textfield is focused

### What is the expected behavior?

> icons shouldn't be focused if I look at the original implementation (https://material-components.github.io/material-components-web-catalog/#/component/text-field)

### What is the actual behavior?

> icon is focused

### Any other information you believe would be useful?

> Maybe make it optional in some way? maybe by specifying a tabindex prop for icons?

**Comment by jetrii** [comment]
Big +1 on this, it's very annoying.
