### ISSUE TITLE
mdc-chip: events not triggered/handled (0.18.1)

### ISSUE THREAD

**Issue by Lampy09** [stasson/vue-mdc-adapter#513]
### What vue-mdc-adapter Version are you using?

> Please be specific, e.g. 0.18.1

### What browser(s) is this bug affecting?

> All

### What OS are you using?

> OSX

### What are the steps to reproduce the bug?

> Use mdc-chip / mdc-chipset and add an event listener:
`<mdc-chip-set>
<mdc-chip trailingIcon="close"  @MDCChip:trailingIconInteraction='removeChip()'>Chip</mdc-chip>
</mdc-chip-set>`

### What is the expected behavior?

> Event `MDCChip:trailingIconInteraction` is fired and `removeChip()` is called

### What is the actual behavior?

> I think `MDCChip:trailingIconInteraction` is fired but it's not handled (or I'm doing something wrong)

### Any other information you believe would be useful?
> It worked in 0.17.x

**Comment by finpingvin** [comment]
Have you tried to add the native modifier? Worked for me, example from my code:
`@MDCChip:removal.native="onTagRemoved"`
Without the native modifier my callback was not called.
