### ISSUE TITLE
mdc-shape: Add support for Shape

### ISSUE THREAD

**Issue by rishabh3112** [stasson/vue-mdc-adapter#528]
## Bugs
Just a feature request

### What is the expected behavior?
`<mdc-shape>` should add angled corners to unelevated components

### What is the actual behavior?
mdc-shape is not supported

### Any other information you believe would be useful?
[Shape for web](https://material.io/develop/web/components/shape/)

**Comment by HelloWorldIL** [comment]
I second that, I haven't seen a single implementation of Material Design that features in-depth theming with shape. Currently using Vuetify and the lack of this feature is a problem.
