### ISSUE TITLE
'top-app-bar' folder missing files

### ISSUE THREAD

**Issue by ashrafhadden** [stasson/vue-mdc-adapter#529]
## Bugs

`top-app-bar` folder only contains `styles.scss` and is missing all of its .js and .css files like every other component has.

### What vue-mdc-adapter Version are you using?

0.18.2

### What browser(s) is this bug affecting?

Chrome 69.0.3497.92 (Official Build) (64-bit)

### What OS are you using?

10.13.6

### What are the steps to reproduce the bug?
> 1. `npm install vue-mdc-adapter`
> 2. look inside `vue-mdc-adapter/dist/top-app-bar`

### What is the expected behavior?

There should be .js and .css files just like in every other component. I double-checked and only `top-app-bar` is missing any files.

### What is the actual behavior?
`top-app-bar` folder only contains `styles.scss`

### Any other information you believe would be useful?
As I posted in https://github.com/stasson/vue-mdc-adapter/issues/461#issuecomment-420859343...

> I'm not sure why but `vue-mdc-adapter` v0.18.2 npm package has a different folder structure > than the one implied by your official documentation where it states:
> 
> > **import a la carte plugins**
> > ```
> > import Vue from 'vue'
> > import VueMDCButton from 'vue-mdc-adapter/button'
> > Vue.use(VueMDCButton)
> > ```
> > https://stasson.github.io/vue-mdc-adapter/#/docs/getting-started
> 
> which would imply `import VueMDCButton from 'node_modules/vue-mdc-adapter/button'`
> but in reality it's `import VueMDCButton from 'node_modules/vue-mdc-adapter/dist/button'`

**Comment by vaaski** [comment]
any update?
