### ISSUE TITLE
Grid layout cell span 0

### ISSUE THREAD

**Issue by sebastian-raubach** [stasson/vue-mdc-adapter#530]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

vue-mdc-adapter is still under active development. You can see our current progress on [master](https://github.com/stasson/vue-mdc-adapter/tree/master).

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What vue-mdc-adapter Version are you using?

0.15.3

### What browser(s) is this bug affecting?

All of them, all versions.

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

```
<mdc-layout-grid>
    <mdc-layout-cell desktop=2 tablet=0 phone=0></mdc-layout-cell>
    <mdc-layout-cell desktop=8 tablet=8 phone=4></mdc-layout-cell>
    <mdc-layout-cell desktop=2 tablet=0 phone=0></mdc-layout-cell>
</mdc-layout-grid>
```

### What is the expected behavior?

First and last cell should be invisible on tablet and phone, but I get an error instead.

### What is the actual behavior?

Invalid prop: custom validator check failed for prop "phone".
Invalid prop: custom validator check failed for prop "tablet".

### Any other information you believe would be useful?

I'm currently migrating from Material Design Lite. They had `mdl-cell--hide-tablet` styles to hide cells on certain devices.

**Comment by fg123** [comment]
Did some more research, guess this isn't possible until upstream implements it: 
https://github.com/material-components/material-components-web/issues/688
https://github.com/material-components/material-components-web/issues/23
