### ISSUE TITLE
"date" type should be supported by <mdc-textfield />

### ISSUE THREAD

**Issue by sheley1998** [stasson/vue-mdc-adapter#544]
code below should work 
`<mdc-textfield type="date" label="date" value="" />`
instead, an error is thrown:  'Invalid prop: custom validator check failed for prop "type".'

**Comment by jetrii** [comment]
Agreed. Here is the validator code that is causing the issue - it just needs to include 'date' 

```
          validator: function validator(value) {
            return ['text', 'email', 'search', 'password', 'tel', 'url', 'number'].indexOf(value) !== -1;
          }
```
