### ISSUE TITLE
Top app bar position relative?

### ISSUE THREAD

**Issue by Larsklopstra** [stasson/vue-mdc-adapter#545]
### What vue-mdc-adapter Version are you using?

> 0.18.2

### What OS are you using?

> Windows 10 home

### What is the expected behavior?

> Position should be relative instead of fixed with fixed being set as `false`.

### What is the actual behavior?

> The component appears to be fixed no matter what.

**Comment by pgbross** [comment]
This might be because the wrong underlying foundation is being used due to a bug in the vue-mdc-adapter top-app-bar implementation.

It is supposed to select between three foundations like this
```
    this.foundation = this.short
      ? new MDCShortTopAppBarFoundation(adapter)
      : this.fixed
        ? new MDCFixedTopAppBarFoundation(adapter)
        : new MDCTopAppBarFoundation(adapter)
```
but currently doesn't.
