### ISSUE TITLE
mdc-top-app-bar Scrolls To Top On Menu Icon Click

### ISSUE THREAD

**Issue by thehendrix** [stasson/vue-mdc-adapter#546]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

vue-mdc-adapter is still under active development. You can see our current progress on [master](https://github.com/stasson/vue-mdc-adapter/tree/master).

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What vue-mdc-adapter Version are you using?

> Please be specific, e.g. _major.minor.patch_

### What browser(s) is this bug affecting?

Every browser

### What OS are you using?

MacOS Mojave

### What are the steps to reproduce the bug?

Just click on the hamburger menu button in the nav bar

### What is the expected behavior?

Not append # to url and not scroll to top of page

### What is the actual behavior?

Appending # to url and scrolling the page to the top

### Any other information you believe would be useful?

All you need to do is remove the href="#" attribute from the <a> element in the mdc-top-app-bar and it will be fixed. It's that simple.

**Comment by pgbross** [comment]
This might be because the wrong underlying foundation is being used due to a bug in the vue-mdc-adapter top-app-bar implementation.

It is supposed to select between three foundations like this
```
    this.foundation = this.short
      ? new MDCShortTopAppBarFoundation(adapter)
      : this.fixed
        ? new MDCFixedTopAppBarFoundation(adapter)
        : new MDCTopAppBarFoundation(adapter)
```
but currently doesn't. In a copy of `vue-mdc-adapter` with basically that code the `mdc-top-app-bar` component does the right thing.

**Comment by thehendrix** [comment]
No that's not the problem. I'm using the 'fixed' mdc-top-app-bar, which means the component will stay at the top of the page even when you scroll up and down the page. This is the correct behavior. The issue is that if I scroll to say the middle of the page and I click the menu button, the page will instantly jump to the top. This is caused because of an href="#". Just looked at the code and the problem is on line 13 of this file:
**vue-mdc-adapter/components/top-app-bar/mdc-top-app-bar.vue**
If you can remove that for me the problem will be fixed and I will love you forever.
:)

**Comment by pgbross** [comment]
Interesting. `vue-mdc-adapter` is wrapping the html recommended by the underlying `material-components-web` framework. In their [documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-top-app-bar) it uses a link element with an href="#".

Do you have a codepen example which demonstrates the problem so it can be investigated?

**Comment by thehendrix** [comment]
I don't, but yes your documentation link shows the exact piece that should be removed. If you load the mdc-top-app-bar Vue SFC and do an inspect on it in your browser you'll see the code you linked me to. If you remove the href="#" in the inspect tool the page will stop scrolling to the top when you click the hamburger button which should be the correct behavior. The href="#" is basically a placeholder for an actual link or an id for the page to scroll to. There is no need for that href="#" in **vue-mdc-adapter/components/top-app-bar/mdc-top-app-bar.vue** on line 13. If someone really needs a link or anchor they should wrap it inside of the mdc-top-app-bar tags in their Vue SFC.

**Comment by pgbross** [comment]
Looking at the material-components-web [demo](https://material-components.github.io/material-components-web-catalog/#/component/top-app-bar/fixed), I see they use a `<button/>` element rather than a `<a/>` element, presumably for the reason you state in your issue.

The `mdc-top-app-bar` `vue-mdc-adapter` component should change to using the `<button/>` element in the next release I agree.

I am currently working through all the other changes to `material-components-web` as well, but hope to have a pull-request soon.

**Comment by thehendrix** [comment]
Any tentative date for when a new release with this fix will happen?

**Comment by maiorano84** [comment]
@thehendrix It appears that this project has been abandoned and is no longer maintained. I would suggest moving to a different package or using this one as a baseline to roll your own implementation.
