### ISSUE TITLE
mdc-textfield outlined css

### ISSUE THREAD

**Issue by eliusxpol** [stasson/vue-mdc-adapter#560]
Hello everyone,
i was trying to use vue-mdc-adapter for a while and did notice that the textfield outline still have a bug when focused.
The textfield i used was simple:
<mdc-textfield v-model="text" label="Hint text" outline/>
when you click on it the textfield border get out the textfield
![initial-textfield](https://user-images.githubusercontent.com/11511172/52521921-ae16be80-2c76-11e9-9235-eead8e9621c4.PNG)
![selected-textfield](https://user-images.githubusercontent.com/11511172/52521925-bbcc4400-2c76-11e9-9ebb-1686fc3fc454.png)

**Comment by Guillaume-Rossignol** [comment]
`<mdc-textfield style="text-align: left" [...] outline />` fixed the bug for me

**Comment by adonaicandido** [comment]
When setting text alignment other than left (eg. center) on a parent element, the SVG inside this component gets moved around.
