### ISSUE TITLE
Webpack Complains 'VueMDCChips' Is Not Defined

### ISSUE THREAD

**Issue by thehendrix** [stasson/vue-mdc-adapter#567]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

vue-mdc-adapter is still under active development. You can see our current progress on [master](https://github.com/stasson/vue-mdc-adapter/tree/master).

## Bugs

VueMDCChips does not exist in vue-mdc-adapter/dist/index.js causing an error when bundling with webpack.

### What vue-mdc-adapter Version are you using?
18.2

### Solution
VueMDCChips is supposed to be VueMDCChipSet

**Comment by VovikeMS** [comment]
I had the same issue.
