### ISSUE TITLE
implement dark theme strategy

### ISSUE THREAD

**Issue by stasson** [stasson/vue-mdc-adapter#61]

**Comment by griest024** [comment]
What is your current strategy for implementing this?

**Comment by stasson** [comment]
First guess : 
- A `theme-dark` property for each component supporting `mdc-xxx--theme-dark`
- a container component or directive for `mdc-theme--dark`

I'm not sure yet. I have not read the MDC doc for a long time now ...

**Comment by stasson** [comment]
> I do not see any visual difference

I think both are suppose to have same visual effect. the difference is only convenience. one acts on the component itself. the other wraps components.

**Comment by griest024** [comment]
> a container component or directive for mdc-theme--dark

I really like the idea of making theme directives.

> A theme-dark property for each component supporting mdc-xxx--theme-dark

Would the prop be a `boolean` so you would just pass `<... :dark-theme="true">` or would we generalize the whole theming feature and pass in an identifier for the prop like `<... :theme="'dark'">`?

If we generalize the theming in that way it would be very helpful to the user for switching themes easily.

**Comment by griest024** [comment]
@stasson What actual things do we need to do to an element for theming. Is it just a matter of having the correct class?

**Comment by stasson** [comment]
I could not find a reference to mdc-theme--dark in MDC packages sources. only in demo so I guess it's not used anymore !?!!

I created a draft of mdc-theme wrapper component.

**Comment by griest024** [comment]
> Alternatively, you can set your entire page (or a portion of it) to a dark theme by using the mdc-theme--dark class

@stasson from [the theming guide](https://material.io/components/web/docs/theming/) at the bottom of the page.

**Comment by stasson** [comment]
yes but it seems that this doc is obsolete. there is no component theming that I could find. only the demo has some customization for dark theme...

**Comment by stasson** [comment]
NA anymore
