### ISSUE TITLE
v0.0.39 won't work with webpack

### ISSUE THREAD

**Issue by ocavue** [stasson/vue-mdc-adapter#70]
Reproduce this bug step by step:

```
➜  [test] date
Mon Sep 25 05:34:15 CST 2017

➜  [test] vue init webpack-simple test_project

➜  [test] cd test_project/

➜  [test_project] npm install 
npm notice created a lockfile as package-lock.json. You should commit this file.
added 733 packages in 59.949s

➜  [test_project] npm install --save vue-mdc-adapter
+ vue-mdc-adapter@0.0.39
added 35 packages in 16.774s

➜  [test_project] vim src/main.js
➜  [test_project] cat src/main.js
import Vue from 'vue'
import App from './App.vue'
import VueMdcAdapter from 'vue-mdc-adapter'
Vue.use(VueMdcAdapter)
new Vue({
  el: '#app',
  render: h => h(App)
})

➜  [test_project] vim src/App.vue 
➜  [test_project] cat src/App.vue 
<template>
  <div id="app">
    <mdc-card>
    </mdc-card>
  </div>
</template>
<script>
export default {
  name: 'app',
  data () { }
}
</script>
<style>
</style>

➜  [test_project] npm run build
ERROR in build.js from UglifyJs
Unexpected token: name (MDCFoundation) [./~/@material/base/foundation.js:20,0][build.js:190,6]

```

**Comment by stasson** [comment]
mmmh :(

**Comment by stasson** [comment]
ok there are couple problems with using webpack simple template from scratch.

- vue-mdc-adapter is distributed both as cjs (package.json:main) or es6 module (package.json:module)
By default, webpack will take the module version which is es6. so babel needs to be run on any vue-mdc-adapter and material dependencies. in the template, node_modules are excluded so the @ material code is not being transpiled and then uglify fails as uglifyjs is only es5.

- then there is the sass issue. in order for people to be able to theme, I have split the sass from the module. so you need to import own sass file:
```sass
// mytheme.scss
$mdc-theme-primary: #212121;
$mdc-theme-accent: #41B883;
$mdc-theme-background: #fff;

@import "vue-mdc-adapter/components/styles";
```
samething here, most of the sass is imported from node_modules so for it to work, you need to add scss loaders rule to the webpack config and make sure configured which proper resolution of node_modules (`includePaths: [path.resolve(__dirname, '../node_modules')]`)

or if you do  not want to play with sass theme, just add the <links> to css in your index.html : 

```html
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">  
    <link rel="stylesheet" href="https://unpkg.com/vue-mdc-adapter/dist/vue-mdc-adapter.min.css">  
```

I guess I need to add doc on how webpack is to be configured ...

**Comment by stasson** [comment]
you can check my cloud9 workspace for this issue https://c9.io/stasson/vue-mdc-adapter-issues 
`npm run build` is fine 

`npm run dev` dosn't seem to work with this webpack simple template. not sure why. probably issue with my cloud9 config...

**Comment by stasson** [comment]
So to resolve this issue I guess I just need to add some more doc on how to build with webapck

If I have some courage left next week,  I may also  create a webpack boilerplate which works with vue-mdc-adapter...

**Comment by ocavue** [comment]
@stasson 

Thank you so much 😍😍 . I will look into your code in c9.io after receiving my credit card and signing up for c9.io. Maybe this weekend.
