### ISSUE TITLE
fix(drawer): fix responsive behavior of the drawer

### ISSUE THREAD

**Issue by rustemgareev** [stasson/vue-mdc-adapter#76]
There is a bug with responsive behavior of drawer module.
Temporary drawer is opened by default on desktop screens.
Permanent drawer (which [turns into temporary one on mobile screens](https://github.com/stasson/vue-mdc-adapter/tree/master/components/drawer#drawer) in vue-mdc-adapter implementation) is opening up on the wrong breakpoints when scaling browser up and down.
Tested on Chrome, Firefox, Microsoft Edge, IE 11. Operating system is Windows 10.

**Comment by stasson** [comment]
> wrong breakpoints when scaling browser up and down

not sure to understand. which breakpoints were you expecting ?

**Comment by rustemgareev** [comment]
Persistent drawer behavior: when opening web page on mobile / tablet breakpoints and scaling browser up to desktop breakpoints, persistent drawer is opened (as expected). When scaling browser down from desktop breakpoint to mobile / tablet, nothing happens, however closing persistent drawer is expected behavior.

**Comment by rustemgareev** [comment]
This bug still exists, but I found the reason:
https://github.com/stasson/vue-mdc-adapter/blob/master/components/drawer/mdc-drawer.vue#L17-L22.
Missing the range of media queries between 840px and 1320px makes drawer behavior inconsistent.
[This](https://github.com/stasson/vue-mdc-adapter/blob/master/components/drawer/mdc-drawer.vue#L17) should be `max-width: 839px` and [this](https://github.com/stasson/vue-mdc-adapter/blob/master/components/drawer/mdc-drawer.vue#L22) - `min-width: 840px`.

**Comment by stasson** [comment]
@rustemgareev 

not sure to follow your point. right now I'm using 2 mq  mobile below 840 and xlarge above 1320. the middle range being covered is both mobiole and xlarge is false. 

why do you say bug still exists ? can you send as way to reproduce ?

**Comment by rustemgareev** [comment]
This is the situation: my browser is zoomed 100%. When I open the page with drawer, it's closed on 100% zoom. When I zoom the page out to 90%, the drawer gets opened. When I zoom in to 100% again, it _should be closed_, but no, drawer gets closed only on 175% zoom. Is it clear?

**Comment by stasson** [comment]
@rustemgareev 

I can't reproduce this on my chrome...

**Comment by rustemgareev** [comment]
@stasson I posted a link to the video on Gitter.
