### ISSUE TITLE
feat(ssr): add compatibility with server-side rendering

### ISSUE THREAD

**Issue by rustemgareev** [stasson/vue-mdc-adapter#77]
I tried to use vue-mdc-adapter with Nuxt.js and I've got an `HTMLElement is not defined` error which comes from ripple's util package:
[https://github.com/stasson/vue-mdc-adapter/blob/master/components/util/ripple.js#L5](https://github.com/stasson/vue-mdc-adapter/blob/master/components/util/ripple.js#L5)
Making vue-mdc-adapter compatible with SSR and Nuxt.js will be a good feature.

**Comment by stasson** [comment]
@rustemgareev 
ok this one should work now.
Let me know if you have other ssr issues

**Comment by stasson** [comment]
waiting for a fix, needs to set ssr:false in the nuxt config
https://nuxtjs.org/guide/plugins#client-side-only
