### ISSUE TITLE
feat(snackbar): add snackbar aligned on the left side of screen

### ISSUE THREAD

**Issue by rustemgareev** [stasson/vue-mdc-adapter#78]
Currently, there is the only implementation of snackbar which is aligned on the center of screen. However, MDC-Web suggests option to align snackbar on the left side (aligned on "start", according to RTL-aware layout). So, prop will be following:
```
<mdc-snackbar align="start">...</mdc-snackbar>
```

**Comment by stasson** [comment]
fixed in v0.0.49
