### ISSUE TITLE
Add option to create link buttons

### ISSUE THREAD

**Issue by Tim15** [stasson/vue-mdc-adapter#79]
In [the MDC docs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button#html-structure), it says that users can use the button style on a link element. 

![screenshot-2017-10-2 material-components material-components-web](https://user-images.githubusercontent.com/11166947/31105588-6fcfde48-a7b3-11e7-8291-3844b36b9cc2.png)

In some cases, it is beneficial to do so, e.g. to get browsers to open links in new tabs, etc.

Would it be possible to add an option to `<mdc-button>` like `link` or `href`, to use an `<a>` element instead of a `<button>` element?

**Comment by stasson** [comment]
Yes it's definitely possible. 
Plan is to add that feature (href prop) back ( i removed it, I had <button> vs <a> accessibility issues)

In the mean time I guess you can do it this way:

```html
<mdc-button @click="location.href=https://vuejs.org" >go to vue</mdc-button>
```

**Comment by stasson** [comment]
@Tim15 
ok I have added the feature for button fab and card action buttons.
Let me know if it works for you. 
Also I have added accessibility
