### ISSUE TITLE
do it support rtl ?

### ISSUE THREAD

**Issue by vahidalvandi** [stasson/vue-mdc-adapter#81]
hello .
do vue-mdc-adaptor support rtl version ?

**Comment by stasson** [comment]
@vahidalvandi 

vue-mdc-adapter is a wrapper arround MDC. so you have the basic rtl support that comes from mdc:

you add the dir="rtl" attributes, any  mdc-xxxx child components will be rtl

```html
<div dir="rtl">
    <!-- Your app markup -->
</div>
```
