### ISSUE TITLE
Meet MDC Frameworks Integration criteria

### ISSUE THREAD

**Issue by MishUshakov** [stasson/vue-mdc-adapter#84]
Hey, great adapter for mdc, does it meet the [MDC criteria](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md)?
If so, please make a pull request to their [repo](https://github.com/material-components/material-components-web).

**Comment by stasson** [comment]
@MishUshakov 

Thanks! 

Yes I believe it meets the MDC criteria. 

I have followed the [advanced aproach](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md#the-advanced-approach-using-foundations-and-adapters) while implementing the adapters.

I'm not sure what you want me to do a pull request for ? can you elaborate ?

**Comment by MishUshakov** [comment]
Since the repository is very good and it looks like it meets criteria, you can make pull request to MDC and they will publish link to repo on their website and GitHub, so more people can discover the repo and collaborate!

**Comment by stasson** [comment]
ok, I'll do that. I still have some quality issue I want to get resolve first.

**Comment by stasson** [comment]
https://github.com/material-components/material-components-web/pull/1552

**Comment by Bobarev** [comment]
Not in the subject: Please add a link to your repository in [Awesome Vue.js](https://github.com/vuejs/awesome-vue). I found your repository absolutely randomly. While I was starting to write my adapter for mdc.

**Comment by stasson** [comment]
@Bobarev 

Ok I'll do that
